/**
 * SVG title block, scale bar, and dimension annotation fragments.
 * All measurements in meters (SVG user units = meters at 1:1).
 * The generator applies a scaling transform to map to paper size.
 */

import type { Point2D } from '@pascal-app/core'
import { toSvgX, toSvgY } from './geometry'

export interface TitleBlockOptions {
  projectName: string
  levelName: string
  date: string
  scale: number         // e.g. 100 for 1:100
  unit: 'metric' | 'imperial'
  drawingWidthM: number  // width of drawing area in meters (world units)
  drawingHeightM: number
  drawingOriginX: number // SVG-space origin of drawing (top-left after padding)
  drawingOriginY: number
}

// Height of the title block strip at the bottom of the sheet (meters world-scale)
export const TITLE_BLOCK_HEIGHT_M = 0.8

/**
 * Generates an SVG fragment string for the title block + scale bar.
 * Positioned at the bottom of the drawing area.
 */
export function generateTitleBlock(opts: TitleBlockOptions): string {
  const {
    projectName,
    levelName,
    date,
    scale,
    unit,
    drawingWidthM,
    drawingHeightM,
    drawingOriginX,
    drawingOriginY,
  } = opts

  const tbY = drawingOriginY + drawingHeightM
  const tbH = TITLE_BLOCK_HEIGHT_M
  const tbW = drawingWidthM

  // Font sizes in world-meter units
  const fontLg = 0.22
  const fontSm = 0.14
  const pad = 0.12

  // Divider line between columns
  const col1X = drawingOriginX + tbW * 0.45
  const col2X = drawingOriginX + tbW * 0.7

  const parts: string[] = []

  // Outer border
  parts.push(
    `<rect x="${drawingOriginX}" y="${tbY}" width="${tbW}" height="${tbH}" ` +
    `fill="white" stroke="#1a1a1a" stroke-width="0.02"/>`,
  )

  // Top border line (separator from drawing)
  parts.push(
    `<line x1="${drawingOriginX}" y1="${tbY}" x2="${drawingOriginX + tbW}" y2="${tbY}" ` +
    `stroke="#1a1a1a" stroke-width="0.03"/>`,
  )

  // Vertical column dividers
  parts.push(
    `<line x1="${col1X}" y1="${tbY}" x2="${col1X}" y2="${tbY + tbH}" stroke="#888" stroke-width="0.01"/>`,
    `<line x1="${col2X}" y1="${tbY}" x2="${col2X}" y2="${tbY + tbH}" stroke="#888" stroke-width="0.01"/>`,
  )

  // Column 1: Project name + level
  parts.push(
    `<text x="${drawingOriginX + pad}" y="${tbY + pad + fontLg}" ` +
    `font-family="Arial,sans-serif" font-size="${fontSm}" fill="#555">PROJECT</text>`,
    `<text x="${drawingOriginX + pad}" y="${tbY + pad + fontLg + fontLg * 1.4}" ` +
    `font-family="Arial,sans-serif" font-size="${fontLg}" font-weight="bold" fill="#1a1a1a" ` +
    `>${escapeXml(projectName)}</text>`,
    `<text x="${drawingOriginX + pad}" y="${tbY + pad + fontLg * 3.2}" ` +
    `font-family="Arial,sans-serif" font-size="${fontSm}" fill="#555">LEVEL</text>`,
    `<text x="${drawingOriginX + pad}" y="${tbY + pad + fontLg * 3.2 + fontLg * 1.3}" ` +
    `font-family="Arial,sans-serif" font-size="${fontLg}" fill="#1a1a1a" ` +
    `>${escapeXml(levelName)}</text>`,
  )

  // Column 2: Scale + date
  const scaleStr = `1 : ${scale}`
  parts.push(
    `<text x="${col1X + pad}" y="${tbY + pad + fontLg}" ` +
    `font-family="Arial,sans-serif" font-size="${fontSm}" fill="#555">SCALE</text>`,
    `<text x="${col1X + pad}" y="${tbY + pad + fontLg * 2.4}" ` +
    `font-family="Arial,sans-serif" font-size="${fontLg}" font-weight="bold" fill="#1a1a1a" ` +
    `>${scaleStr}</text>`,
    `<text x="${col1X + pad}" y="${tbY + pad + fontLg * 4.2}" ` +
    `font-family="Arial,sans-serif" font-size="${fontSm}" fill="#555">DATE</text>`,
    `<text x="${col1X + pad}" y="${tbY + pad + fontLg * 5.6}" ` +
    `font-family="Arial,sans-serif" font-size="${fontSm}" fill="#1a1a1a" ` +
    `>${escapeXml(date)}</text>`,
  )

  // Column 3: Scale bar
  const sbFragment = generateScaleBar({
    originX: col2X + pad,
    originY: tbY + tbH / 2,
    unit,
  })
  parts.push(sbFragment)

  // Pascal branding (bottom-right)
  parts.push(
    `<text x="${drawingOriginX + tbW - pad}" y="${tbY + tbH - pad}" ` +
    `font-family="Arial,sans-serif" font-size="${fontSm * 0.85}" fill="#aaa" text-anchor="end" ` +
    `>Generated by Pascal Editor</text>`,
  )

  return parts.join('\n')
}

interface ScaleBarOptions {
  originX: number
  originY: number
  unit: 'metric' | 'imperial'
}

/**
 * Generates a scale bar SVG fragment.
 * The bar is drawn in world-meter units — the parent transform handles scale.
 * At 1:100 in SVG, 1 world-meter = 1 SVG user unit = 1mm on paper at 1:1000 scale…
 * The generator sets up viewBox so world units map correctly to paper mm.
 */
function generateScaleBar({ originX, originY, unit }: ScaleBarOptions): string {
  const parts: string[] = []
  const font = 0.12
  const barH = 0.08

  if (unit === 'metric') {
    // 5-segment bar: 0, 1, 2, 3, 4, 5 meters
    const totalW = 5    // 5 meters
    const segW = 1      // 1 meter per segment

    parts.push(
      `<rect x="${originX}" y="${originY - barH / 2}" width="${totalW}" height="${barH}" ` +
      `fill="none" stroke="#1a1a1a" stroke-width="0.015"/>`,
    )

    for (let i = 0; i < 5; i++) {
      if (i % 2 === 0) {
        parts.push(
          `<rect x="${originX + i * segW}" y="${originY - barH / 2}" width="${segW}" height="${barH}" ` +
          `fill="#1a1a1a"/>`,
        )
      }
    }

    // Tick labels
    for (let i = 0; i <= 5; i++) {
      parts.push(
        `<text x="${originX + i * segW}" y="${originY + barH / 2 + font * 1.4}" ` +
        `font-family="Arial,sans-serif" font-size="${font}" text-anchor="middle" fill="#1a1a1a" ` +
        `>${i}m</text>`,
      )
    }
  } else {
    // Imperial: 0–15 feet, 5ft segments (converted: 1ft ≈ 0.3048m)
    const ft = 0.3048
    const totalW = 15 * ft
    const segW = 5 * ft

    parts.push(
      `<rect x="${originX}" y="${originY - barH / 2}" width="${totalW}" height="${barH}" ` +
      `fill="none" stroke="#1a1a1a" stroke-width="0.015"/>`,
    )

    for (let i = 0; i < 3; i++) {
      if (i % 2 === 0) {
        parts.push(
          `<rect x="${originX + i * segW}" y="${originY - barH / 2}" width="${segW}" height="${barH}" ` +
          `fill="#1a1a1a"/>`,
        )
      }
    }

    for (let i = 0; i <= 3; i++) {
      parts.push(
        `<text x="${originX + i * segW}" y="${originY + barH / 2 + font * 1.4}" ` +
        `font-family="Arial,sans-serif" font-size="${font}" text-anchor="middle" fill="#1a1a1a" ` +
        `>${i * 5}ft</text>`,
      )
    }
  }

  return parts.join('\n')
}

/**
 * Generates dimension annotation SVG for a wall segment.
 * offset: how far (in meters) to place the dimension line from the wall centre.
 */
export function generateWallDimension(
  start: Point2D,
  end: Point2D,
  offsetDir: Point2D,
  offsetDist: number,
  unit: 'metric' | 'imperial',
): string {
  const svgS = { x: toSvgX(start.x), y: toSvgY(start.y) }
  const svgE = { x: toSvgX(end.x), y: toSvgY(end.y) }

  const dx = svgE.x - svgS.x
  const dy = svgE.y - svgS.y
  const length = Math.sqrt(dx * dx + dy * dy)
  if (length < 0.05) return ''

  // Offset direction in SVG space (perpendicular to wall)
  const offX = toSvgX(offsetDir.x) * offsetDist
  const offY = toSvgY(offsetDir.y) * offsetDist

  const x1 = svgS.x + offX
  const y1 = svgS.y + offY
  const x2 = svgE.x + offX
  const y2 = svgE.y + offY

  // Label
  const realLength = Math.sqrt(
    (end.x - start.x) ** 2 + (end.y - start.y) ** 2,
  )
  const label =
    unit === 'metric'
      ? realLength >= 1
        ? `${realLength.toFixed(2)}m`
        : `${(realLength * 100).toFixed(0)}cm`
      : `${(realLength / 0.3048).toFixed(1)}ft`

  const midX = (x1 + x2) / 2
  const midY = (y1 + y2) / 2
  const angle = (Math.atan2(dy, dx) * 180) / Math.PI
  const font = 0.12

  const parts = [
    // Dimension line
    `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#555" stroke-width="0.01" stroke-dasharray="0.05 0.03"/>`,
    // Extension lines
    `<line x1="${svgS.x}" y1="${svgS.y}" x2="${x1}" y2="${y1}" stroke="#aaa" stroke-width="0.008"/>`,
    `<line x1="${svgE.x}" y1="${svgE.y}" x2="${x2}" y2="${y2}" stroke="#aaa" stroke-width="0.008"/>`,
    // Label
    `<text x="${midX}" y="${midY}" font-family="Arial,sans-serif" font-size="${font}" ` +
    `text-anchor="middle" dominant-baseline="central" fill="#555" ` +
    `transform="rotate(${angle},${midX},${midY})">${label}</text>`,
  ]

  return parts.join('\n')
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}
