import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import type { SceneOperations } from '../operations'

export const AGENT_GUIDE = [
  '# Pascal MCP Agent Guide',
  '',
  'You are editing Pascal architectural projects. Use MCP tools only; do not inspect the Pascal repository unless the user explicitly asks.',
  '',
  '## Standard Workflow',
  '',
  '1. Read this guide or call `get_capabilities` if available.',
  '2. If the user asks for a new project, call `create_project` first.',
  '3. For quick starts, call `create_house_from_brief`. For precise edits, build with semantic tools: `create_story_shell`, `create_room`, `add_door`, `add_window`, `furnish_room`, `create_roof`, `place_item`.',
  '4. Let semantic tools update the browser-visible draft. Call `save_scene` with `saveMode: "draft"` for autosave-style progress, or `saveMode: "checkpoint"` only for meaningful milestones.',
  '5. Call `validate_scene`, `verify_scene`, then `get_project_status`.',
  '6. Return the final `editorUrl` from tool output. Do not infer routes.',
  '',
  '## Important Concepts',
  '',
  '- A project is the browser-visible container.',
  '- A scene graph is the architectural model.',
  '- A draft is the browser-visible working model and may be overwritten many times.',
  '- A version/checkpoint is a meaningful saved model revision.',
  '- The browser editor opens the current draft when one exists, otherwise the published version.',
  '- Always return the `editorUrl`, not an internal API URL.',
  '',
  '## URLs',
  '',
  '- Use `editorUrl` returned by tools.',
  '- If a tool returns only an id, call `get_project_status` to get the browser URL.',
  '- Hosted editor URLs use `/editor/<projectId>`.',
  '',
  '## Scene Creation Rules',
  '',
  '- Prefer semantic tools over raw graph patches.',
  '- Do not hand-write node graphs unless no semantic tool exists.',
  '- For rooms, use `create_room` -> `add_door` -> `add_window` -> `furnish_room`.',
  '- For complete homes, create exterior shell, interior rooms, openings, roof, furniture, then landscaping.',
  '- For doors/windows, use `t` or `position` from 0 to 1 along the wall unless a tool explicitly says otherwise.',
  '- X/Z are floor-plan axes and Y is vertical; dimensions are meters.',
  '- Use `create_roof` for roofs. A dedicated roof support level is valid and should not count as an occupied story.',
  '',
  '## Formwork',
  '',
  '- Formwork is the temporary shuttering concrete is cast against, and it is a different model from the building: the walls, columns and slabs are what gets built, the formwork is what builds them.',
  '- Start at `list_castable_elements`. It is every wall, column and slab with its dimensions and construction properties in one call, so you do not need a `get_node` per element to find the ids the other tools take. Scope it with `levelId`.',
  '- Read its `unshuttered` list before you quote any total. An element with no `formworkType` is not shuttered and is absent from every bill, and a bill of what exists reads as complete — so a floor short by three walls totals cleanly with nothing in the figures to show it. Name those elements to the user instead of quoting the total alone.',
  '- Nothing is formed until `set_element_construction` gives an element a `formworkType`. Ask the user which system the job uses rather than guessing: plywood, aluminium and steel-panel have different tie grids, different weights and different costs, so a guessed system produces a complete and wrong bill.',
  '- `set_element_construction` states the design and builds nothing. Follow it with `attach_formwork` on the same element or the shutter never exists — the reply says so when it is outstanding, and that sentence is the one thing between a stated wall and a silent gap in the takeoff.',
  '- `castOrder` is a formwork input, not a note. A face butting concrete that is already hard is not formed, so changing the sequence changes the shutters and the bill. `edgeFaceCount` and `soffitHeightAboveSupport` are slab fields and are refused on a wall or column rather than ignored.',
  '- `set_pour_limits` and `attach_formwork` are a pair. Limits decide how many separate pours an element is cast in, and each pour needs its own shutter; setting a limit builds nothing, and attaching without one forms a 9 m wall as a single impossible pour. Set the limits, then attach.',
  '- `attach_formwork` reconciles rather than appends: called again it keeps the shutters whose pour still exists, builds the missing ones, and removes the ones whose pour is gone. Removal discards any per-part decisions recorded on those shutters, and the count in the reply is the only trace of them — pass it on to the user rather than reporting the rebuild as done.',
  '- `inspect_pour_units` is why a joint is where it is. The unit count is the shutter count, so it is how you check an element is formed for the way it is cast, and each unit carries the reason for its cuts as a sentence. Read `volumeCuM` as one delivery, not as a share of a total: it is what the plant has to supply before the first concrete placed sets, and adding the units makes a 3-lift wall read as pourable in one go. The order total is `totalVolumeCuM`.',
  '- `inspect_project_formwork` is the bill — what a scope needs, what it weighs, what to order. Scope it with `levelId`, because a yard orders for a floor and two per-element bills of the same panel cannot be added together afterwards.',
  '- `validate_formwork` is a different question: whether it can be erected at all. A bill can total perfectly for a shutter nobody can put up.',
  '- Neither answer can be derived from the scene graph. Both are properties of a solved panel layout, a pressure calculation and a drilled tie grid, and none of those is a node — so do not attempt either from `get_scene`.',
  '- One thing is set for the whole project rather than per element: the pour itself. The rate of rise, the concrete temperature, the mix, the pressure code and the parts catalog are decisions about a job, not about a wall. Read them with `inspect_formwork_settings` before quoting any pressure, tie spacing or prop spacing, because it also says which figures the job stated and which the engine assumed — a spacing derived from an assumed 7 m/h at 20 °C is not a number the job has agreed to, and presenting it as one is the failure this tool exists to prevent.',
  '- Write them with `set_formwork_settings`, and ask for the rate of rise, the temperature and the code rather than guessing: the whole design hangs off those three. It re-designs every shutter in the scene on its own, so do not offer to regenerate anything — just re-read the bill before repeating a figure you already quoted.',
  '- `curing.surfaceTemperatureC` is the concrete surface while it cures, not `placement.concreteTemperatureC`, which is the mix as it arrives. The two move the design in opposite directions — a colder mix raises the pressure, a colder cure lengthens how long every hired part is held — so never write one for the other.',
  '- `inspect_formwork_parts` is one element, part by part, and it is not a smaller bill — what it carries that a bill cannot is the marks. A mark like `P-A-1-01800` is derived from the part’s own position, so it is a stable handle to quote to the user and the only way to name a part to `set_formwork_part`. Use `inspect_project_formwork` for anything to be ordered; one element is rarely the scope a yard is asking about.',
  '- `set_formwork_part` records the two decisions a yard actually makes about a solved layout: substitute a catalog item, or leave a part off the order because it is already on site. Sizes, lengths, spacings and utilisations are outputs of the design — change those through `set_formwork_settings` and read the parts again. Ask before substituting: a panel from another manufacturer’s system will not line up with this system’s tie holes.',
  '- Never merge `errorCount` and `warningCount`: an error is something the crew cannot do, a warning is an exception somebody has to sign.',
  '- Always report `notChecked` and `caveats`. A list of failures alone reads as a clean bill of health for everything that was never examined, and a caveat means every figure under it is wrong in a way the figures cannot show.',
  '- `supply` on the bill is the owned/hired split, and it is absent where nobody has recorded what the yard owns — say that rather than implying the whole bill is on hire. The split covers one scope only, because the same owned panels serve the next pour once stripped, so never add two levels’ owned figures; and `hiredAlteredHere` is a recharge at list price, not a hire charge.',
  '- A period is not a date. The striking tables say a wall form comes off in 12 hours; only a pour date says which morning the plant is wanted and which afternoon it is free for the next pour. `set_pour_date` records it, and it takes an assembly id from the bill’s `schedule.pours` rather than an element id — a date is per pour, and a 9 m wall in three lifts is three dates a week apart.',
  '- Never infer a pour date. Nothing in this model computes a programme from dependencies or float, so there is no sequence to read one off, and a date derived from the order the shutters happen to be in prints beside geometry that genuinely is derived and carries the same authority. Ask the user. Where nothing is dated the bill carries no `schedule` at all, and where only some pours are dated `undatedPours` says how much of the job the window leaves out.',
  '- Two lead times turn the dates into a delivery, both on `set_formwork_settings schedule`: days before a pour that the plant is wanted, and days after striking before it is back with the hire company. Both calendar days rather than working days, because a hire is charged over a weekend. Without the first there is no delivery date; without the second the bill shows plant free the day it is struck, which is a floor rather than an answer.',
  '- `schedule.daysOnSite` is arrival to release across every pour and is not `hire.longestDaysHeld`, which is one pour’s hold: a set used on five pours a week apart is held two days each time and on site for five weeks. The on-site figure is the one a yard invoices. A pour’s `strikeAt` is the last of its strikes, not the first, because it is the day the set comes free — a slab’s deck comes off days before its props.',
  '- Run `validate_formwork` before presenting a takeoff as an order.',
  '',
  '## Required Final Checks',
  '',
  '- `save_scene` must succeed. Use `saveMode: "checkpoint"` before final handoff only if the user asked for a durable version.',
  '- `verify_scene.hasIssues` should be false; otherwise explain remaining issues.',
  '- `get_project_status.nodeCount` must be greater than 0 for a non-empty design.',
  '- Return `editorUrl` in the final user response.',
  '',
  '## If Something Looks Empty',
  '',
  '1. Call `get_project_status`.',
  '2. Compare `publishedVersion`, `latestVersion`, `browserVisibleVersion`, `nodeCount`, and `graphHash`.',
  '3. If the graph is non-empty but the browser appears empty, call `get_project_status` to re-bind the session, then `save_scene` with `saveMode: "draft"`.',
  '4. Re-run `verify_scene`.',
  '',
  '## Output Contract',
  '',
  'Final user response should include: project name, `editorUrl`, version, node/room summary, and any known limitations.',
].join('\n')

export function registerAgentGuide(server: McpServer, _bridge: SceneOperations): void {
  server.registerResource(
    'agent-guide',
    'pascal://agent-guide',
    {
      title: 'Pascal MCP agent guide',
      description:
        'Short MCP-first project creation, save/publish, validation, and output workflow for external agents.',
      mimeType: 'text/markdown',
    },
    async (uri) => ({
      contents: [
        {
          uri: uri.href,
          mimeType: 'text/markdown',
          text: AGENT_GUIDE,
        },
      ],
    }),
  )

  server.registerResource(
    'agent-guide-legacy',
    'pascal://agent/guide',
    {
      title: 'Pascal MCP agent guide',
      description: 'Legacy URI for the Pascal MCP agent guide. Prefer pascal://agent-guide.',
      mimeType: 'text/markdown',
    },
    async (uri) => ({
      contents: [
        {
          uri: uri.href,
          mimeType: 'text/markdown',
          text: AGENT_GUIDE,
        },
      ],
    }),
  )
}
