import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import type { SceneOperations } from '../operations'

export const AGENT_GUIDE = [
  '# Pascal MCP Agent Guide',
  '',
  'You are editing Pascal architectural projects. Use MCP tools only; do not inspect the Pascal repository unless the user explicitly asks.',
  '',
  '## Standard Workflow',
  '',
  '1. Read this guide or call `get_capabilities` if available.',
  '2. If the user asks for a new project, call `create_project` first.',
  '3. For quick starts, call `create_house_from_brief`. For precise edits, build with semantic tools: `create_story_shell`, `create_room`, `add_door`, `add_window`, `furnish_room`, `create_roof`, `place_item`.',
  '4. Let semantic tools update the browser-visible draft. Call `save_scene` with `saveMode: "draft"` for autosave-style progress, or `saveMode: "checkpoint"` only for meaningful milestones.',
  '5. Call `validate_scene`, `verify_scene`, then `get_project_status`.',
  '6. Return the final `editorUrl` from tool output. Do not infer routes.',
  '',
  '## Important Concepts',
  '',
  '- A project is the browser-visible container.',
  '- A scene graph is the architectural model.',
  '- A draft is the browser-visible working model and may be overwritten many times.',
  '- A version/checkpoint is a meaningful saved model revision.',
  '- The browser editor opens the current draft when one exists, otherwise the published version.',
  '- Always return the `editorUrl`, not an internal API URL.',
  '',
  '## URLs',
  '',
  '- Use `editorUrl` returned by tools.',
  '- If a tool returns only an id, call `get_project_status` to get the browser URL.',
  '- Hosted editor URLs use `/editor/<projectId>`.',
  '',
  '## Scene Creation Rules',
  '',
  '- Prefer semantic tools over raw graph patches.',
  '- Do not hand-write node graphs unless no semantic tool exists.',
  '- For rooms, use `create_room` -> `add_door` -> `add_window` -> `furnish_room`.',
  '- For complete homes, create exterior shell, interior rooms, openings, roof, furniture, then landscaping.',
  '- For doors/windows, use `t` or `position` from 0 to 1 along the wall unless a tool explicitly says otherwise.',
  '- X/Z are floor-plan axes and Y is vertical; dimensions are meters.',
  '- Use `create_roof` for roofs. A dedicated roof support level is valid and should not count as an occupied story.',
  '',
  '## Formwork',
  '',
  '- Formwork is the temporary shuttering concrete is cast against, and it is a different model from the building: the walls, columns and slabs are what gets built, the formwork is what builds them.',
  '- `inspect_project_formwork` is the bill — what a scope needs, what it weighs, what to order. Scope it with `levelId`, because a yard orders for a floor and two per-element bills of the same panel cannot be added together afterwards.',
  '- `validate_formwork` is a different question: whether it can be erected at all. A bill can total perfectly for a shutter nobody can put up.',
  '- Neither answer can be derived from the scene graph. Both are properties of a solved panel layout, a pressure calculation and a drilled tie grid, and none of those is a node — so do not attempt either from `get_scene`.',
  '- One thing is set for the whole project rather than per element: the pour itself. The rate of rise, the concrete temperature, the mix, the pressure code and the parts catalog are decisions about a job, not about a wall. Read them with `inspect_formwork_settings` before quoting any pressure, tie spacing or prop spacing, because it also says which figures the job stated and which the engine assumed — a spacing derived from an assumed 7 m/h at 20 °C is not a number the job has agreed to, and presenting it as one is the failure this tool exists to prevent.',
  '- Write them with `set_formwork_settings`, and ask for the rate of rise, the temperature and the code rather than guessing: the whole design hangs off those three. It re-designs every shutter in the scene on its own, so do not offer to regenerate anything — just re-read the bill before repeating a figure you already quoted.',
  '- `curing.surfaceTemperatureC` is the concrete surface while it cures, not `placement.concreteTemperatureC`, which is the mix as it arrives. The two move the design in opposite directions — a colder mix raises the pressure, a colder cure lengthens how long every hired part is held — so never write one for the other.',
  '- Never merge `errorCount` and `warningCount`: an error is something the crew cannot do, a warning is an exception somebody has to sign.',
  '- Always report `notChecked` and `caveats`. A list of failures alone reads as a clean bill of health for everything that was never examined, and a caveat means every figure under it is wrong in a way the figures cannot show.',
  '- `supply` on the bill is the owned/hired split, and it is absent where nobody has recorded what the yard owns — say that rather than implying the whole bill is on hire. The split covers one scope only, because the same owned panels serve the next pour once stripped, so never add two levels’ owned figures; and `hiredAlteredHere` is a recharge at list price, not a hire charge.',
  '- Run `validate_formwork` before presenting a takeoff as an order.',
  '',
  '## Required Final Checks',
  '',
  '- `save_scene` must succeed. Use `saveMode: "checkpoint"` before final handoff only if the user asked for a durable version.',
  '- `verify_scene.hasIssues` should be false; otherwise explain remaining issues.',
  '- `get_project_status.nodeCount` must be greater than 0 for a non-empty design.',
  '- Return `editorUrl` in the final user response.',
  '',
  '## If Something Looks Empty',
  '',
  '1. Call `get_project_status`.',
  '2. Compare `publishedVersion`, `latestVersion`, `browserVisibleVersion`, `nodeCount`, and `graphHash`.',
  '3. If the graph is non-empty but the browser appears empty, call `get_project_status` to re-bind the session, then `save_scene` with `saveMode: "draft"`.',
  '4. Re-run `verify_scene`.',
  '',
  '## Output Contract',
  '',
  'Final user response should include: project name, `editorUrl`, version, node/room summary, and any known limitations.',
].join('\n')

export function registerAgentGuide(server: McpServer, _bridge: SceneOperations): void {
  server.registerResource(
    'agent-guide',
    'pascal://agent-guide',
    {
      title: 'Pascal MCP agent guide',
      description:
        'Short MCP-first project creation, save/publish, validation, and output workflow for external agents.',
      mimeType: 'text/markdown',
    },
    async (uri) => ({
      contents: [
        {
          uri: uri.href,
          mimeType: 'text/markdown',
          text: AGENT_GUIDE,
        },
      ],
    }),
  )

  server.registerResource(
    'agent-guide-legacy',
    'pascal://agent/guide',
    {
      title: 'Pascal MCP agent guide',
      description: 'Legacy URI for the Pascal MCP agent guide. Prefer pascal://agent-guide.',
      mimeType: 'text/markdown',
    },
    async (uri) => ({
      contents: [
        {
          uri: uri.href,
          mimeType: 'text/markdown',
          text: AGENT_GUIDE,
        },
      ],
    }),
  )
}
