export { loadPlugin, nodeRegistry, registerNode } from './registry'
export { createSceneApi, type SceneStoreLike } from './scene-api'
export type {
  Affordance,
  AnyNodeDefinition,
  AssetRef,
  Capabilities,
  CapabilityCtx,
  CuttableConfig,
  DragAction,
  EditorCtx,
  HostableConfig,
  Issue,
  LazyComponent,
  McpOverrides,
  Modifiers,
  MovableConfig,
  NodeCategory,
  NodeDefinition,
  NodeRegistry,
  ParametricDescriptor,
  ParamField,
  ParamGroup,
  Plugin,
  Relations,
  RendererSource,
  RotatableConfig,
  ScalableConfig,
  SceneApi,
  SelectableConfig,
  SnappableConfig,
  SnapPointKind,
  SnapServicesLike,
  SurfacePoint,
  SurfaceQuery,
  SurfacesConfig,
  SystemContribution,
  Vec2,
} from './types'
