'use client'

import type { CSSProperties, SVGProps } from 'react'
import {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArchiveRestore,
  ArrowDownUp,
  Badge,
  Bot,
  Box,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleDot,
  ClipboardCheck,
  CloudDownload,
  Cone,
  Crosshair,
  Cuboid,
  DatabaseZap,
  Diamond,
  DoorOpen,
  Download,
  ExternalLink,
  Factory,
  FileText,
  GitBranch,
  Grid2X2,
  Grid3X3,
  Group,
  History,
  ImagePlus,
  Import,
  Info,
  Keyboard,
  Layers2,
  Lightbulb,
  LoaderCircle,
  LockKeyhole,
  Magnet,
  Mouse,
  MousePointer2,
  MousePointerClick,
  Move,
  OctagonAlert,
  Package,
  PackageCheck,
  PackageOpen,
  PackagePlus,
  PanelBottomOpen,
  PanelTopOpen,
  Pencil,
  Pill,
  Play,
  Plus,
  RefreshCw,
  Route,
  Rotate3D,
  Scan,
  Scissors,
  Send,
  Settings2,
  Shapes,
  ShieldAlert,
  Square,
  StepForward,
  Tag,
  Trash2,
  TreePine,
  Upload,
  UploadCloud,
  Waypoints,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react'

type LocalIconProps = Omit<SVGProps<SVGSVGElement>, 'color'> & {
  icon?: string | { body?: string }
  width?: number | string
  height?: number | string
  color?: string
  style?: CSSProperties
}

const ICON_MAP: Record<string, LucideIcon> = {
  'carbon:cut-out': Scissors,
  'charm:stack-pop': PanelTopOpen,
  'charm:stack-push': PanelBottomOpen,
  'icon-park-outline:arrow-keys': Keyboard,
  'icon-park-outline:perspective': Box,
  'lucide:diamond': Diamond,
  'lucide:fence': Square,
  'lucide:grid-2x2': Grid2X2,
  'lucide:space': Keyboard,
  'lucide:x': X,
  'mdi:alert': AlertTriangle,
  'mdi:alert-circle-outline': AlertCircle,
  'mdi:alert-octagon-outline': OctagonAlert,
  'mdi:alert-outline': AlertTriangle,
  'mdi:archive-arrow-up-outline': UploadCloud,
  'mdi:archive-plus-outline': ArchiveRestore,
  'mdi:archive': Archive,
  'mdi:arrow-collapse-vertical': PanelBottomOpen,
  'mdi:arrow-decision-outline': Waypoints,
  'mdi:arrow-expand-vertical': PanelTopOpen,
  'mdi:axis-arrow': Move,
  'mdi:cancel': X,
  'mdi:check': Check,
  'mdi:check-circle-outline': CircleCheck,
  'mdi:chevron-down': ChevronDown,
  'mdi:chevron-right': ChevronRight,
  'mdi:circle-double': CircleDot,
  'mdi:circle-outline': Circle,
  'mdi:cloud-download-outline': CloudDownload,
  'mdi:close': X,
  'mdi:clipboard-check-outline': ClipboardCheck,
  'mdi:cone': Cone,
  'mdi:cone-off': Cone,
  'mdi:cube-outline': Cuboid,
  'mdi:cube-scan': Scan,
  'mdi:cube-send': Send,
  'mdi:cursor-default-click-outline': MousePointerClick,
  'mdi:database-search-outline': DatabaseZap,
  'mdi:debug-step-over': StepForward,
  'mdi:download': Download,
  'mdi:door': DoorOpen,
  'mdi:factory': Factory,
  'mdi:file-document-outline': FileText,
  'mdi:format-color-fill': Badge,
  'mdi:group': Group,
  'mdi:history': History,
  'mdi:image-auto-adjust': ImagePlus,
  'mdi:image-plus-outline': ImagePlus,
  'mdi:image-sync-outline': ImagePlus,
  'mdi:import': Import,
  'mdi:information-outline': Info,
  'mdi:lightbulb-outline': Lightbulb,
  'mdi:layers-outline': Layers2,
  'mdi:loading': LoaderCircle,
  'mdi:lock-alert-outline': LockKeyhole,
  'mdi:magnet': Magnet,
  'mdi:open-in-new': ExternalLink,
  'mdi:package-variant': Package,
  'mdi:package-variant-closed': PackageCheck,
  'mdi:package-variant-plus': PackagePlus,
  'mdi:package-variant-remove': PackageOpen,
  'mdi:pencil-outline': Pencil,
  'mdi:pill': Pill,
  'mdi:play': Play,
  'mdi:play-circle-outline': Play,
  'mdi:plus': Plus,
  'mdi:progress-clock': History,
  'mdi:rectangle-rounded-outline': Square,
  'mdi:refresh': RefreshCw,
  'mdi:replay': RefreshCw,
  'mdi:robot-industrial': Bot,
  'mdi:robot-industrial-outline': Bot,
  'mdi:rotate-3d': Rotate3D,
  'mdi:routes': Route,
  'mdi:select-drag': MousePointer2,
  'mdi:send': Send,
  'mdi:shape-outline': Shapes,
  'mdi:shape-plus': Shapes,
  'mdi:shape-polygon-plus': Shapes,
  'mdi:shield-alert-outline': ShieldAlert,
  'mdi:slope-uphill': Move,
  'mdi:sphere': Circle,
  'mdi:source-branch': GitBranch,
  'mdi:stop': Square,
  'mdi:swap-horizontal-bold': ArrowDownUp,
  'mdi:tag-text-outline': Tag,
  'mdi:target': Crosshair,
  'mdi:tools': Wrench,
  'mdi:transit-connection-variant': Waypoints,
  'mdi:trash-can-outline': Trash2,
  'mdi:tree-outline': TreePine,
  'mdi:tune-variant': Settings2,
  'mdi:upload': Upload,
  'mdi:vector-curve': Waypoints,
  'mdi:vector-polyline': Waypoints,
  'mdi:window-closed-variant': Square,
  'ph:mouse-left-click-fill': MousePointerClick,
  'ph:mouse-right-click-fill': Mouse,
  'qlementine-icons:mouse-middle-button-16': Mouse,
  'vaadin:grid': Grid3X3,
}

function iconName(icon: LocalIconProps['icon']) {
  return typeof icon === 'string' ? icon : ''
}

export function Icon({ icon, width, height, color, className, style, ...props }: LocalIconProps) {
  const name = iconName(icon)
  const Component = ICON_MAP[name] ?? Circle
  const sizeStyle: CSSProperties = {
    width: width ?? undefined,
    height: height ?? undefined,
    color,
    ...style,
  }

  return (
    <Component
      aria-hidden={props['aria-hidden'] ?? true}
      className={className}
      color={color}
      focusable="false"
      size={typeof width === 'number' && width === height ? width : undefined}
      style={sizeStyle}
      {...props}
    />
  )
}

export default Icon
