/**
 * Hand-built DXF fragments. ASCII DXF is a flat stream of (code, value) line
 * pairs, so fixtures are readable enough to write literally — which matters,
 * because a fixture generated by the same assumptions as the parser would
 * prove nothing.
 */

export function pair(code: number, value: string | number): string {
  return `${code}\n${value}\n`
}

export function section(name: string, body: string): string {
  return pair(0, 'SECTION') + pair(2, name) + body + pair(0, 'ENDSEC')
}

export function dxf(...sections: string[]): string {
  return sections.join('') + pair(0, 'EOF')
}

export function header(vars: Record<string, [number, number | string]> = {}): string {
  let body = ''
  for (const [name, [code, value]] of Object.entries(vars)) {
    body += pair(9, name) + pair(code, value)
  }
  return section('HEADER', body)
}

export function layerTable(
  layers: { name: string; color?: number; flags?: number }[] = [],
): string {
  let body = pair(0, 'TABLE') + pair(2, 'LAYER') + pair(70, layers.length)
  for (const layer of layers) {
    body += pair(0, 'LAYER') + pair(2, layer.name)
    body += pair(70, layer.flags ?? 0)
    body += pair(62, layer.color ?? 7)
  }
  body += pair(0, 'ENDTAB')
  return section('TABLES', body)
}

export function entities(body: string): string {
  return section('ENTITIES', body)
}

export function line(
  layer: string,
  x1: number,
  y1: number,
  x2: number,
  y2: number,
  extra = '',
): string {
  return (
    pair(0, 'LINE') +
    pair(8, layer) +
    pair(10, x1) +
    pair(20, y1) +
    pair(30, 0) +
    pair(11, x2) +
    pair(21, y2) +
    pair(31, 0) +
    extra
  )
}

export function arc(
  layer: string,
  cx: number,
  cy: number,
  radius: number,
  startDeg: number,
  endDeg: number,
): string {
  return (
    pair(0, 'ARC') +
    pair(8, layer) +
    pair(10, cx) +
    pair(20, cy) +
    pair(30, 0) +
    pair(40, radius) +
    pair(50, startDeg) +
    pair(51, endDeg)
  )
}

export function circle(layer: string, cx: number, cy: number, radius: number): string {
  return (
    pair(0, 'CIRCLE') +
    pair(8, layer) +
    pair(10, cx) +
    pair(20, cy) +
    pair(30, 0) +
    pair(40, radius)
  )
}

export function lwpolyline(
  layer: string,
  vertices: { x: number; y: number; bulge?: number }[],
  closed = false,
): string {
  let out =
    pair(0, 'LWPOLYLINE') + pair(8, layer) + pair(90, vertices.length) + pair(70, closed ? 1 : 0)
  for (const vertex of vertices) {
    out += pair(10, vertex.x) + pair(20, vertex.y)
    if (vertex.bulge !== undefined) out += pair(42, vertex.bulge)
  }
  return out
}

/** The pre-R13 polyline form: a POLYLINE header, VERTEX children, a SEQEND. */
export function polyline(
  layer: string,
  vertices: { x: number; y: number; bulge?: number }[],
  closed = false,
): string {
  let out = pair(0, 'POLYLINE') + pair(8, layer) + pair(66, 1) + pair(70, closed ? 1 : 0)
  for (const vertex of vertices) {
    out += pair(0, 'VERTEX') + pair(8, layer) + pair(10, vertex.x) + pair(20, vertex.y)
    if (vertex.bulge !== undefined) out += pair(42, vertex.bulge)
  }
  out += pair(0, 'SEQEND') + pair(8, layer)
  return out
}

export function block(name: string, baseX: number, baseY: number, body: string): string {
  return (
    pair(0, 'BLOCK') +
    pair(2, name) +
    pair(70, 0) +
    pair(10, baseX) +
    pair(20, baseY) +
    pair(30, 0) +
    body +
    pair(0, 'ENDBLK')
  )
}

export function insert(
  layer: string,
  name: string,
  x: number,
  y: number,
  options: { scaleX?: number; scaleY?: number; rotation?: number } = {},
): string {
  return (
    pair(0, 'INSERT') +
    pair(8, layer) +
    pair(2, name) +
    pair(10, x) +
    pair(20, y) +
    pair(30, 0) +
    pair(41, options.scaleX ?? 1) +
    pair(42, options.scaleY ?? 1) +
    pair(43, 1) +
    pair(50, options.rotation ?? 0)
  )
}

/** Read segment `i` out of the flat coordinate array. */
export function segmentAt(
  segments: Float64Array | Float32Array,
  i: number,
): [number, number, number, number] {
  return [segments[i * 4]!, segments[i * 4 + 1]!, segments[i * 4 + 2]!, segments[i * 4 + 3]!]
}

export function ellipse(
  layer: string,
  cx: number,
  cy: number,
  majorX: number,
  majorY: number,
  ratio: number,
  startParam = 0,
  endParam = Math.PI * 2,
): string {
  return (
    pair(0, 'ELLIPSE') +
    pair(8, layer) +
    pair(10, cx) +
    pair(20, cy) +
    pair(30, 0) +
    pair(11, majorX) +
    pair(21, majorY) +
    pair(31, 0) +
    pair(40, ratio) +
    pair(41, startParam) +
    pair(42, endParam)
  )
}

export function spline(
  layer: string,
  controlPoints: [number, number][],
  {
    degree = 3,
    knots,
    weights,
    closed = false,
  }: { degree?: number; knots?: number[]; weights?: number[]; closed?: boolean } = {},
): string {
  // A clamped uniform knot vector, which is what almost every writer emits.
  const resolvedKnots =
    knots ??
    (() => {
      const n = controlPoints.length
      const interior = n - degree - 1
      const out: number[] = []
      for (let i = 0; i <= degree; i++) out.push(0)
      for (let i = 1; i <= interior; i++) out.push(i / (interior + 1))
      for (let i = 0; i <= degree; i++) out.push(1)
      return out
    })()

  let body = pair(0, 'SPLINE') + pair(8, layer) + pair(70, closed ? 1 : 0) + pair(71, degree)
  body += pair(72, resolvedKnots.length) + pair(73, controlPoints.length)
  for (const knot of resolvedKnots) body += pair(40, knot)
  if (weights) for (const weight of weights) body += pair(41, weight)
  for (const [x, y] of controlPoints) body += pair(10, x) + pair(20, y) + pair(30, 0)
  return body
}
