/**
 * Preset lots — PlanCrafters' `presetlots.js` (HA.PRESET_LOTS), ported
 * verbatim: a curated menu of REAL US addresses for testing the generator
 * and the site pipeline on varied lots without fighting the address search.
 * Each carries a pre-geocoded lat/lng so the drop-in resolves the parcel
 * straight off the state layer (the coordinate point-in-polygon path).
 *
 * Every entry was live-resolved against the parcel registry by PlanCrafters
 * and its `lotNote` reflects the recorded parcel. Coverage: CA statewide
 * (site-index exact); AZ-Maricopa, GA-Fulton, IL-Cook metros; CO / MT / NC /
 * NV / UT / WA statewide; the "+" tail adds TX / FL / TN / OR / SC metros.
 *   flat 🟩 · rolling 🌾 · hilly ⛰️ · mountain 🏔️ · desert 🏜️ · coastal 🌊
 */
export type PresetTerrain = 'flat' | 'rolling' | 'hilly' | 'mountain' | 'desert' | 'coastal'

export interface PresetLot {
  label: string
  badge: string
  address1: string
  address2: string
  city: string
  state: string
  zip: string
  lat: number
  lng: number
  terrain: PresetTerrain
  lotNote: string
}

export const PRESET_LOTS: readonly PresetLot[] = [
  // ---- California (statewide, site-index exact) ----
  {
    label: 'Sacramento, CA — Land Park',
    badge: '🟩',
    address1: '2600 Castro Way',
    address2: 'Sacramento, CA 95818',
    city: 'Sacramento',
    state: 'CA',
    zip: '95818',
    lat: 38.553517,
    lng: -121.480667,
    terrain: 'flat',
    lotNote: '~5,300 SF flat 50×107 urban lot',
  },
  {
    label: 'Sacramento, CA — Stockton Blvd',
    badge: '🟩',
    address1: '3258 Stockton Blvd',
    address2: 'Sacramento, CA 95817',
    city: 'Sacramento',
    state: 'CA',
    zip: '95817',
    lat: 38.545081,
    lng: -121.452985,
    terrain: 'flat',
    lotNote: '~12,500 SF larger flat corner lot',
  },
  {
    label: 'Sacramento, CA — Oak Park',
    badge: '🟩',
    address1: '3400 5th Ave',
    address2: 'Sacramento, CA 95817',
    city: 'Sacramento',
    state: 'CA',
    zip: '95817',
    lat: 38.549118,
    lng: -121.470948,
    terrain: 'flat',
    lotNote: '~9,900 SF flat urban bungalow lot',
  },
  {
    label: 'Winton, CA — Central Valley',
    badge: '🟩',
    address1: '6660 W Olive Ave',
    address2: 'Winton, CA 95388',
    city: 'Winton',
    state: 'CA',
    zip: '95388',
    lat: 37.396721,
    lng: -120.607935,
    terrain: 'flat',
    lotNote: '~6,100 SF flat rural-town lot',
  },
  {
    label: 'Placerville, CA — Gold Country',
    badge: '⛰️',
    address1: '5328 Overland Way',
    address2: 'Placerville, CA 95667',
    city: 'Placerville',
    state: 'CA',
    zip: '95667',
    lat: 38.691899,
    lng: -120.60899,
    terrain: 'hilly',
    lotNote: '~2.5-acre rolling Sierra foothill parcel',
  },
  {
    label: 'Tahoe City, CA — north shore',
    badge: '🏔️',
    address1: '2565 Lake Forest Rd',
    address2: 'Tahoe City, CA 96145',
    city: 'Tahoe City',
    state: 'CA',
    zip: '96145',
    lat: 39.184131,
    lng: -120.11733,
    terrain: 'mountain',
    lotNote: '~4,950 SF forested mountain lot',
  },
  {
    label: 'Palm Springs, CA — desert',
    badge: '🏜️',
    address1: '1033 E Tachevah Dr',
    address2: 'Palm Springs, CA 92262',
    city: 'Palm Springs',
    state: 'CA',
    zip: '92262',
    lat: 33.837571,
    lng: -116.536175,
    terrain: 'desert',
    lotNote: '~10,100 SF flat desert lot',
  },
  {
    label: 'La Jolla, CA — Mt Soledad',
    badge: '🌊',
    address1: '7455 Hillside Dr',
    address2: 'La Jolla, CA 92037',
    city: 'La Jolla',
    state: 'CA',
    zip: '92037',
    lat: 32.844549,
    lng: -117.255885,
    terrain: 'coastal',
    lotNote: '~18,600 SF (0.43-ac) coastal hillside',
  },
  // ---- Arizona (Maricopa) ----
  {
    label: 'Phoenix, AZ — NE suburb',
    badge: '🏜️',
    address1: '4127 E Anderson Dr',
    address2: 'Phoenix, AZ 85032',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85032',
    lat: 33.642361,
    lng: -111.992456,
    terrain: 'desert',
    lotNote: '~4,150 SF narrow 40-ft desert lot',
  },
  {
    label: 'Scottsdale, AZ — McDowell foothills',
    badge: '🏜️',
    address1: '15984 N 106th Way',
    address2: 'Scottsdale, AZ 85255',
    city: 'Scottsdale',
    state: 'AZ',
    zip: '85255',
    lat: 33.631251,
    lng: -111.852228,
    terrain: 'desert',
    lotNote: '~6,900 SF foothills desert lot',
  },
  // ---- Nevada ----
  {
    label: 'Henderson, NV — Seven Hills',
    badge: '🏜️',
    address1: '1677 Warrington Dr',
    address2: 'Henderson, NV 89052',
    city: 'Henderson',
    state: 'NV',
    zip: '89052',
    lat: 35.96455,
    lng: -115.108196,
    terrain: 'desert',
    lotNote: '~7,800 SF flat desert tract lot',
  },
  // ---- Utah ----
  {
    label: 'Salt Lake City, UT — Avenues',
    badge: '⛰️',
    address1: '165 B St',
    address2: 'Salt Lake City, UT 84103',
    city: 'Salt Lake City',
    state: 'UT',
    zip: '84103',
    lat: 40.773195,
    lng: -111.882124,
    terrain: 'hilly',
    lotNote: '~2,500 SF narrow historic bench lot',
  },
  // ---- Colorado ----
  {
    label: 'Boulder, CO — Flagstaff',
    badge: '🏔️',
    address1: '7127 Flagstaff Rd',
    address2: 'Boulder, CO 80302',
    city: 'Boulder',
    state: 'CO',
    zip: '80302',
    lat: 39.966205,
    lng: -105.337516,
    terrain: 'mountain',
    lotNote: '~2.75-acre steep forested mountain lot',
  },
  // ---- Montana ----
  {
    label: 'Bozeman, MT — valley acreage',
    badge: '🏔️',
    address1: '7521 Jarmen Cir',
    address2: 'Bozeman, MT 59715',
    city: 'Bozeman',
    state: 'MT',
    zip: '59715',
    lat: 45.593896,
    lng: -111.055145,
    terrain: 'mountain',
    lotNote: '~2.5-acre valley/foothill acreage',
  },
  // ---- Washington ----
  {
    label: 'Issaquah, WA — Cougar Mtn',
    badge: '⛰️',
    address1: '873 Cougar Mountain Ln NW',
    address2: 'Issaquah, WA 98027',
    city: 'Issaquah',
    state: 'WA',
    zip: '98027',
    lat: 47.540968,
    lng: -122.073203,
    terrain: 'hilly',
    lotNote: '~5,800 SF steep wooded ridge lot',
  },
  // ---- North Carolina ----
  {
    label: 'Asheville, NC — Town Mtn',
    badge: '🏔️',
    address1: '2771 Town Mountain Rd',
    address2: 'Asheville, NC 28804',
    city: 'Asheville',
    state: 'NC',
    zip: '28804',
    lat: 35.635801,
    lng: -82.496143,
    terrain: 'mountain',
    lotNote: '~2.2-acre steep Blue Ridge lot',
  },
  {
    label: 'Cary, NC — Lochmere',
    badge: '🟩',
    address1: '1105 Queensferry Rd',
    address2: 'Cary, NC 27511',
    city: 'Cary',
    state: 'NC',
    zip: '27511',
    lat: 35.741977,
    lng: -78.805059,
    terrain: 'flat',
    lotNote: '~0.56-acre flat Triangle suburban lot',
  },
  // ---- Georgia (Fulton) ----
  {
    label: 'Atlanta, GA — Buckhead',
    badge: '🌾',
    address1: '2836 Margaret Mitchell Dr NW',
    address2: 'Atlanta, GA 30327',
    city: 'Atlanta',
    state: 'GA',
    zip: '30327',
    lat: 33.834274,
    lng: -84.43556,
    terrain: 'rolling',
    lotNote: '~0.65-acre wooded rolling lot',
  },
  {
    label: 'Alpharetta, GA — north Fulton',
    badge: '🌾',
    address1: '145 Welford Trace',
    address2: 'Alpharetta, GA 30004',
    city: 'Alpharetta',
    state: 'GA',
    zip: '30004',
    lat: 34.077299,
    lng: -84.342972,
    terrain: 'rolling',
    lotNote: '~0.71-acre wooded rolling estate lot',
  },
  // ---- Illinois (Cook — narrowest) ----
  {
    label: 'Chicago, IL — Avondale',
    badge: '🟩',
    address1: '3415 N Troy St',
    address2: 'Chicago, IL 60618',
    city: 'Chicago',
    state: 'IL',
    zip: '60618',
    lat: 41.943175,
    lng: -87.706442,
    terrain: 'flat',
    lotNote: '~3,000 SF (24-ft) narrow city lot',
  },
  // ---- PRESET LOTS+ (coordinate point-in-polygon states) ----
  {
    label: 'Austin, TX — Circle C Ranch',
    badge: '🌾',
    address1: '6112 Zachary Scott St',
    address2: 'Austin, TX 78749',
    city: 'Austin',
    state: 'TX',
    zip: '78749',
    lat: 30.216512,
    lng: -97.856317,
    terrain: 'rolling',
    lotNote: '~8,300 SF gently rolling SW-suburb tract lot',
  },
  {
    label: 'Houston, TX — Meyerland',
    badge: '🟩',
    address1: '5122 Braesheather Dr',
    address2: 'Houston, TX 77096',
    city: 'Houston',
    state: 'TX',
    zip: '77096',
    lat: 29.678488,
    lng: -95.472621,
    terrain: 'flat',
    lotNote: '~9,000 SF dead-flat bayou-plain ranch lot',
  },
  {
    label: 'Miami Shores, FL — bayside',
    badge: '🌊',
    address1: '1247 NE 104th St',
    address2: 'Miami Shores, FL 33138',
    city: 'Miami Shores',
    state: 'FL',
    zip: '33138',
    lat: 25.875961,
    lng: -80.174093,
    terrain: 'coastal',
    lotNote: '~10,000 SF low coastal lot near Biscayne Bay',
  },
  {
    label: 'Nashville, TN — Green Hills',
    badge: '🌾',
    address1: '4009 Lealand Ln',
    address2: 'Nashville, TN 37204',
    city: 'Nashville',
    state: 'TN',
    zip: '37204',
    lat: 36.096705,
    lng: -86.78415,
    terrain: 'rolling',
    lotNote: '~0.4-acre rolling mid-town Tennessee lot',
  },
  {
    label: 'Phoenix, AZ — Arcadia acre',
    badge: '🏜️',
    address1: '5719 E Calle Del Paisano',
    address2: 'Phoenix, AZ 85018',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85018',
    lat: 33.507968,
    lng: -111.961564,
    terrain: 'desert',
    lotNote: '~1-acre flat irrigated desert estate lot',
  },
  {
    label: 'Portland, OR — SW hills',
    badge: '🌾',
    address1: '7231 SW 33rd Ave',
    address2: 'Portland, OR 97219',
    city: 'Portland',
    state: 'OR',
    zip: '97219',
    lat: 45.463996,
    lng: -122.712556,
    terrain: 'rolling',
    lotNote: '~7,500 SF rolling wooded westside lot',
  },
  {
    label: 'Golden, CO — Genesee foothills',
    badge: '⛰️',
    address1: '23610 Genesee Village Rd',
    address2: 'Golden, CO 80401',
    city: 'Golden',
    state: 'CO',
    zip: '80401',
    lat: 39.686161,
    lng: -105.276481,
    terrain: 'hilly',
    lotNote: '~0.5-acre pine foothill lot west of Denver',
  },
  {
    label: 'Charleston, SC — historic peninsula',
    badge: '🟩',
    address1: '32 Legare St',
    address2: 'Charleston, SC 29401',
    city: 'Charleston',
    state: 'SC',
    zip: '29401',
    lat: 32.77186,
    lng: -79.935293,
    terrain: 'flat',
    lotNote: '~6,500 SF flat historic-district lot below sea-breeze line',
  },
]

/** The drop-in input for a preset: its coordinates skip geocoding. */
export function presetDropInInput(p: PresetLot) {
  return {
    address: `${p.address1}, ${p.address2}`,
    latitude: p.lat,
    longitude: p.lng,
    state: p.state,
    street: p.address1,
    city: p.city,
    zip: p.zip,
  }
}
