import { AssetInput, ItemNode } from "@pascal-app/core";
export const CATALOG_ITEMS: AssetInput[] = [
  {
    category: "furniture",
    name: "Couch",
    thumbnail: "/items/couch-medium/thumbnail.webp",
    src: "/items/couch-medium/model.glb",
    scale: [0.35, 0.35, 0.35],
    dimensions: [2, 0.8, 1],
  },
  {
    category: "furniture",
    name: "Small Couch",
    thumbnail: "/items/couch-small/thumbnail.webp",
    src: "/items/couch-small/model.glb",
    scale: [0.35, 0.35, 0.35],
    dimensions: [1, 0.8, 1],
  },
  {
    category: "furniture",
    name: "Desk",
    thumbnail: "/items/desk/thumbnail.webp",
    src: "/items/desk/model.glb",
    scale: [1, 1, 1],
    dimensions: [4, 2, 2],
  },
  {
    category: "furniture",
    name: "Table",
    thumbnail: "/items/table/thumbnail.webp",
    src: "/items/table/model.glb",
    scale: [1, 1, 1],
    rotation: [0, Math.PI / 2, 0],
    dimensions: [6, 2, 3],
  },
  {
    category: "outdoor",
    name: "Fence",
    thumbnail: "/items/fence/thumbnail.webp",
    src: "/items/fence/model.glb",
    scale: [0.8, 0.8, 0.8],
    offset: [0, 0, -0.12],
    rotation: [0, Math.PI, 0],
    dimensions: [6, 2, 1],
  },
  {
    category: "outdoor",
    name: "Parking Spot",
    thumbnail: "/items/parking-spot/thumbnail.webp",
    src: "/items/parking-spot/model.glb",
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, Math.PI, 0],
    dimensions: [12, 2, 6],
  },
  {
    category: "outdoor",
    name: "Hedge",
    thumbnail: "/items/hedge/thumbnail.webp",
    src: "/items/hedge/model.glb",
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, Math.PI, 0],
    dimensions: [4, 2, 3],
  },
  {
    category: "outdoor",
    name: "Tree",
    thumbnail: "/items/tree/thumbnail.webp",
    src: "/items/tree/model.glb",
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, Math.PI, 0],
    dimensions: [2, 2, 2],
  },
  {
    category: "appliance",
    name: "Ceiling Light",
    thumbnail: "/items/ceiling-light/thumbnail.webp",
    src: "/items/ceiling-light/model.glb",
    scale: [1, 1, 1],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
    attachTo: "ceiling",
  },
  {
    category: "appliance",
    name: "Ceiling Fan",
    thumbnail: "/items/ceiling-fan/thumbnail.webp",
    src: "/items/ceiling-fan/model.glb",
    scale: [0.003, 0.003, 0.003],
    offset: [0, -0.62, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
    attachTo: "ceiling",
  },
  {
    category: "appliance",
    name: "Rectangular Ceiling Light",
    thumbnail: "/items/rectangular-ceiling-light/thumbnail.webp",
    src: "/items/rectangular-ceiling-light/model.glb",
    scale: [0.04, 0.04, 0.04],
    offset: [0.2, -0.1, 0.95],
    rotation: [0, Math.PI / 2, 0],
    dimensions: [2, 2, 4],
    attachTo: "ceiling",
  },
  {
    category: "appliance",
    name: "Circular Ceiling Light",
    thumbnail: "/items/circular-ceiling-light/thumbnail.webp",
    src: "/items/circular-ceiling-light/model.glb",
    scale: [1, 1, 1],
    offset: [0, -0.1, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
    attachTo: "ceiling",
  },
  {
    category: "appliance",
    name: "Smoke Detector",
    thumbnail: "/items/smoke-detector/thumbnail.webp",
    src: "/items/smoke-detector/model.glb",
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [Math.PI, 0, 0],
    dimensions: [1, 2, 1],
    attachTo: "ceiling",
  },
  {
    category: "appliance",
    name: "Sprinkler",
    thumbnail: "/items/sprinkler/thumbnail.webp",
    src: "/items/sprinkler/model.glb",
    scale: [3, 3, 3],
    offset: [0, 0, 0],
    rotation: [Math.PI, 0, 0],
    dimensions: [1, 2, 1],
    attachTo: "ceiling",
  },
  {
    category: "appliance",
    name: "Exit Sign",
    thumbnail: "/items/exit-sign/thumbnail.webp",
    src: "/items/exit-sign/model.glb",
    scale: [0.5, 0.5, 0.5],
    offset: [0, -0.3, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
    attachTo: "ceiling",
  },
  {
    category: "furniture",
    name: "Wall Art",
    thumbnail: "/items/wall-art-06/thumbnail.webp",
    src: "/items/wall-art-06/model.glb",
    offset: [0, 0.5, 0],
    scale: [1, 1, 1],
    rotation: [0, Math.PI, 0],
    dimensions: [1, 1, 0.1],
    attachTo: "wall-side",
  },
  {
    category: "furniture",
    name: "Flat Screen TV",
    thumbnail: "/items/flat-screen-tv/thumbnail.webp",
    src: "/items/flat-screen-tv/model.glb",
    offset: [-0.2, 1, 0.15],
    scale: [0.42, 0.42, 0.42],
    rotation: [0, 0, 0],
    dimensions: [4, 2, 1],
    attachTo: "wall-side",
  },
  {
    category: "appliance",
    name: "Air Conditioner",
    thumbnail: "/items/air-conditioner/thumbnail.webp",
    src: "/items/air-conditioner/model.glb",
    offset: [0, 2, 0.3],
    scale: [0.0015, 0.0015, 0.0015],
    rotation: [0, 0, 0],
    dimensions: [3, 2, 1],
    attachTo: "wall-side",
  },
  {
    category: "appliance",
    name: "AC Block",
    thumbnail: "/items/ac-block/thumbnail.webp",
    src: "/items/ac-block/model.glb",
    offset: [0, 0, 0],
    scale: [1, 1, 1],
    rotation: [0, Math.PI, 0],
    dimensions: [3, 2, 3],
  },
  {
    category: "appliance",
    name: "Fire extinguisher",
    thumbnail: "/items/fire-extinguisher/thumbnail.webp",
    src: "/items/fire-extinguisher/model.glb",
    offset: [0, 1.5, 0.22],
    scale: [0.8, 0.8, 0.8],
    rotation: [0, -Math.PI / 2, 0],
    dimensions: [1, 2, 1],
    attachTo: "wall-side",
  },
  {
    category: "appliance",
    name: "Fire alarm ",
    thumbnail: "/items/fire-alarm/thumbnail.webp",
    src: "/items/fire-alarm/model.glb",
    offset: [0, 1, 0.14],
    scale: [0.15, 0.15, 0.15],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
    attachTo: "wall-side",
  },
  {
    category: "appliance",
    name: "Fire detector ",
    thumbnail: "/items/fire-detector/thumbnail.webp",
    src: "/items/fire-detector/model.glb",
    offset: [0, 1.1, 0.14],
    scale: [2, 2, 2],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
    attachTo: "wall-side",
  },
  {
    category: "appliance",
    name: "Alarm keypad",
    thumbnail: "/items/alarm-keypad/thumbnail.webp",
    src: "/items/alarm-keypad/model.glb",
    offset: [0, 1.2, 0.1],
    scale: [2, 2, 2],
    rotation: [Math.PI / 2, 0, 0],
    dimensions: [1, 2, 1],
    attachTo: "wall-side",
  },
  {
    category: "appliance",
    name: "Thermostat",
    thumbnail: "/items/thermostat/thumbnail.webp",
    src: "/items/thermostat/model.glb",
    offset: [0, 1.2, 0.1],
    scale: [5, 5, 5],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
    attachTo: "wall-side",
  },
  {
    category: "appliance",
    name: "Electric panel",
    thumbnail: "/items/electric-panel/thumbnail.webp",
    src: "/items/electric-panel/model.glb",
    offset: [0, 0.4, 0.16],
    scale: [1, 1, 1],
    rotation: [0, 0, 0],
    dimensions: [2, 1, 1],
    attachTo: "wall-side",
  },
  {
    category: "appliance",
    name: "Air Conditioner Block",
    thumbnail: "/items/air-conditioner-block/thumbnail.webp",
    src: "/items/air-conditioner-block/model.glb",
    offset: [0, 0.5, -0.06],
    scale: [1, 1, 1],
    rotation: [0, 0, 0],
    dimensions: [2, 2, 2],
    attachTo: "wall-side",
  },
  {
    category: "kitchen",
    name: "Kitchen Fridge",
    thumbnail: "/items/kitchen-fridge/thumbnail.webp",
    src: "/items/kitchen-fridge/model.glb",
    offset: [0, 0, 0.0],
    scale: [0.7, 0.7, 0.7],
    rotation: [0, 0, 0],
    dimensions: [2, 2, 2],
  },
  {
    category: "kitchen",
    name: "Freezer",
    thumbnail: "/items/freezer/thumbnail.webp",
    src: "/items/freezer/model.glb",
    offset: [-0.43, 0, 0.25],
    scale: [1.8, 1.8, 1.8],
    rotation: [0, Math.PI, 0],
    dimensions: [2, 1, 1],
  },
  {
    category: "bathroom",
    name: "Wall Sink",
    thumbnail: "/items/wall-sink/thumbnail.webp",
    src: "/items/wall-sink/model.glb",
    offset: [0, 0, 0.25],
    scale: [0.7, 0.7, 0.7],
    rotation: [0, 0, 0],
    dimensions: [2, 1, 1],
    attachTo: "wall-side",
  },
  {
    category: "kitchen",
    name: "Sink with cabinet",
    thumbnail: "/items/sink-cabinet/thumbnail.webp",
    src: "/items/sink-cabinet/model.glb",
    offset: [0, 0.5, 0],
    scale: [1.4, 1.4, 1.4],
    rotation: [0, 0, 0],
    dimensions: [4, 2, 1],
  },
  {
    category: "bathroom",
    name: "Toilet",
    thumbnail: "/items/toilet/thumbnail.webp",
    src: "/items/toilet/model.glb",
    offset: [0, 0, -0.1],
    scale: [0.005, 0.005, 0.005],
    rotation: [0, -Math.PI / 4, 0],
    dimensions: [1, 2, 1],
  },
  {
    category: "window",
    name: "Window",
    thumbnail: "/items/window-small/thumbnail.webp",
    src: "/items/window-small/model.glb",
    offset: [0, 0.15, 0],
    scale: [1, 1, 1],
    rotation: [0, Math.PI, 0],
    dimensions: [1, 1.5, 0.1],
    attachTo: "wall",
  },
  {
    category: "window",
    name: "Window",
    thumbnail: "/items/window-small-2/thumbnail.webp",
    src: "/items/window-small-2/model.glb",
    offset: [0, 0, 0],
    scale: [1, 1, 1],
    rotation: [0, Math.PI, 0],
    dimensions: [1, 1, 0.1],
    attachTo: "wall",
  },
  {
    category: "window",
    name: "Window",
    thumbnail: "/items/window-round/thumbnail.webp",
    src: "/items/window-round/model.glb",
    offset: [0, 0.5, 0],
    scale: [1, 1, 1],
    rotation: [0, Math.PI, 0],
    dimensions: [2, 1, 1],
    attachTo: "wall",
  },
  {
    category: "window",
    name: "Window",
    thumbnail: "/items/window1-black-open-1731/thumbnail.webp",
    src: "/items/window1-black-open-1731/model.glb",
    offset: [0, 0.5, 0],
    scale: [0.4, 0.4, 0.4],
    rotation: [0, 0, 0],
    dimensions: [2, 1, 1],
    attachTo: "wall",
  },
  {
    category: "door",
    name: "Door",
    thumbnail: "/items/doorway-front/thumbnail.webp",
    src: "/items/doorway-front/model.glb",
    offset: [0, 0, 0],
    scale: [2, 2, 2],
    rotation: [0, Math.PI, 0],
    dimensions: [2, 1, 1],
    attachTo: "wall",
  },
  {
    category: "door",
    name: "Door",
    thumbnail: "/items/door/thumbnail.webp",
    src: "/items/door/model.glb",
    offset: [0, 0, 0],
    scale: [0.2, 0.2, 0.2],
    rotation: [0, Math.PI, 0],
    dimensions: [2, 1, 1],
    attachTo: "wall",
  },
  {
    category: "door",
    name: "Door with bar",
    thumbnail: "/items/door-with-bar/thumbnail.webp",
    src: "/items/door-with-bar/model.glb",
    offset: [0, 0, 0],
    scale: [0.65, 0.65, 0.65],
    rotation: [0, Math.PI, 0],
    dimensions: [2, 1, 1],
    attachTo: "wall",
  },
];
