import type { AssetInput } from '@pascal-app/core/schema'

/**
 * Built-in catalog for standalone/headless MCP use (133 items).
 *
 * The editor has a larger UI catalog (`packages/editor/.../catalog-items.tsx`),
 * but depending on `@pascal-app/editor` from the MCP package would pull
 * browser/React code into the headless server. This is a synced subset:
 * stable IDs and asset URLs mirrored directly from the editor's curated
 * 'system' library items only (user-uploaded/community items excluded).
 * Re-sync manually if the editor catalog gains more useful items.
 */
export const MCP_CATALOG_ITEMS: AssetInput[] = [
  {
    id: 'double-bed',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Double Bed',
    thumbnail: '/items/double-bed/thumbnail.webp',
    src: '/items/double-bed/model.glb',
    dimensions: [1.35, 0.6707, 2],
    offset: [-0.675, 0, 1],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'single-bed',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Single Bed',
    thumbnail: '/items/single-bed/thumbnail.webp',
    src: '/items/single-bed/model.glb',
    dimensions: [0.9, 0.6707, 2],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bedside-table',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Bedside Table',
    thumbnail: '/items/bedside-table/thumbnail.webp',
    src: '/items/bedside-table/model.glb',
    dimensions: [0.5, 0.5, 0.5],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.5 },
  },
  {
    id: 'dresser',
    category: 'furniture',
    tags: ['floor', 'storage', 'bedroom'],
    name: 'Dresser',
    thumbnail: '/items/dresser/thumbnail.webp',
    src: '/items/dresser/model.glb',
    dimensions: [0.5, 0.9, 0.5319],
    offset: [0, 0, -0.016],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.9 },
  },
  {
    id: 'closet',
    category: 'furniture',
    tags: ['floor', 'storage', 'bedroom'],
    name: 'Closet',
    thumbnail: '/items/closet/thumbnail.webp',
    src: '/items/closet/model.glb',
    dimensions: [1.2, 2, 0.6186],
    offset: [-0.0349, 0, -0.0093],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa',
    category: 'furniture',
    tags: ['floor', 'seating', 'living'],
    name: 'Sofa',
    thumbnail: '/items/sofa/thumbnail.webp',
    src: '/items/sofa/model.glb',
    dimensions: [1.8, 0.8675, 0.93],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa-single',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'compact', 'single-seat'],
    name: 'Single Seat Sofa',
    thumbnail: '/items/sofa-single/thumbnail.webp',
    src: '/items/sofa-single/model.glb',
    dimensions: [0.9, 0.8675, 0.93],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa-three-seat',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'three-seat'],
    name: 'Three Seat Sofa',
    thumbnail: '/items/sofa-three-seat/thumbnail.webp',
    src: '/items/sofa-three-seat/model.glb',
    dimensions: [2.4, 0.8675, 0.93],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa-t-01',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'sofa', 'couch', 'against-wall', 'three-seat'],
    name: 'Sofa T 01',
    thumbnail: '/items/sofa-t-01/thumbnail.webp',
    src: '/items/sofa-t-01/model.glb',
    dimensions: [2.4, 0.5, 0.9],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa-t-02',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'sofa', 'couch', 'against-wall', 'compact', 'two-seat'],
    name: 'Sofa T 02',
    thumbnail: '/items/sofa-t-02/thumbnail.webp',
    src: '/items/sofa-t-02/model.glb',
    dimensions: [1.957, 0.815, 0.562],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa-t-03',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'sofa', 'couch', 'against-wall', 'three-seat'],
    name: 'Sofa T 03',
    thumbnail: '/items/sofa-t-03/thumbnail.webp',
    src: '/items/sofa-t-03/model.glb',
    dimensions: [2.33, 0.875, 0.824],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa-t-04',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'sofa', 'couch', 'against-wall', 'large', 'sectional'],
    name: 'Sofa T 04',
    thumbnail: '/items/sofa-t-04/thumbnail.webp',
    src: '/items/sofa-t-04/model.glb',
    dimensions: [3.144, 0.853, 2],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa-t-05',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'sofa', 'couch', 'against-wall', 'large', 'three-seat'],
    name: 'Sofa T 05',
    thumbnail: '/items/sofa-t-05/thumbnail.webp',
    src: '/items/sofa-t-05/model.glb',
    dimensions: [2.87, 0.859, 0.991],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'livingroom-chair',
    category: 'furniture',
    tags: ['floor', 'seating', 'living'],
    name: 'Livingroom Chair',
    thumbnail: '/items/livingroom-chair/thumbnail.webp',
    src: '/items/livingroom-chair/model.glb',
    dimensions: [1.5, 0.8, 1.5],
    offset: [0.01, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'coffee-table',
    category: 'furniture',
    tags: ['floor', 'table', 'living'],
    name: 'Coffee Table',
    thumbnail: '/items/coffee-table/thumbnail.webp',
    src: '/items/coffee-table/model.glb',
    dimensions: [1.2012, 0.5, 0.45],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.5 },
  },
  {
    id: 'tv-stand',
    category: 'furniture',
    tags: ['floor', 'storage', 'living'],
    name: 'TV Stand',
    thumbnail: '/items/tv-stand/thumbnail.webp',
    src: '/items/tv-stand/model.glb',
    dimensions: [2, 0.4, 0.5],
    offset: [0, 0.21, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.36 },
  },
  {
    id: 'shelf',
    category: 'furniture',
    tags: ['wall', 'storage'],
    name: 'Shelf',
    thumbnail: '/items/shelf/thumbnail.webp',
    src: '/items/shelf/model.glb',
    dimensions: [1, 0.5, 0.7],
    offset: [0, 0.1, 0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
    surface: { height: 0.12 },
  },
  {
    id: 'dining-table',
    category: 'furniture',
    tags: ['floor', 'table', 'dining'],
    name: 'Dining Table',
    thumbnail: '/items/dining-table/thumbnail.webp',
    src: '/items/dining-table/model.glb',
    dimensions: [1.85, 0.751, 0.9],
    offset: [-0.0024, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.751 },
  },
  {
    id: 'dining-chair',
    category: 'furniture',
    tags: ['floor', 'seating', 'dining'],
    name: 'Dining Chair',
    thumbnail: '/items/dining-chair/thumbnail.webp',
    src: '/items/dining-chair/model.glb',
    dimensions: [0.5, 1, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen',
    category: 'kitchen',
    tags: ['floor', 'large', 'kitchen'],
    name: 'Kitchen',
    thumbnail: '/items/kitchen/thumbnail.webp',
    src: '/items/kitchen/model.glb',
    dimensions: [2.5, 1.1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-counter',
    category: 'kitchen',
    tags: ['floor', 'large', 'storage', 'kitchen'],
    name: 'Kitchen Counter',
    thumbnail: '/items/kitchen-counter/thumbnail.webp',
    src: '/items/kitchen-counter/model.glb',
    dimensions: [3.07, 1.0287, 1.29],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 1.0287 },
  },
  {
    id: 'kitchen-countertop-stove',
    category: 'kitchen',
    tags: [
      'floor',
      'kitchen',
      'countertop',
      'counter',
      'stove',
      'cooktop',
      'range',
      'hob',
      'burner',
      'cooking',
      'appliance',
      'cabinet',
      'against-wall',
      '灶台',
      '燃气灶',
    ],
    name: 'Kitchen Countertop Stove',
    thumbnail: '/items/kitchen-countertop-stove/thumbnail.webp',
    src: '/items/kitchen-countertop-stove/model.glb',
    dimensions: [2.614, 0.624, 1.256],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.624 },
  },
  {
    id: 'kitchen-countertop-stove-03',
    category: 'kitchen',
    tags: [
      'floor',
      'kitchen',
      'countertop',
      'counter',
      'stove',
      'cooktop',
      'range',
      'hob',
      'burner',
      'cooking',
      'appliance',
      'cabinet',
      'against-wall',
      '灶台',
      '燃气灶',
    ],
    name: 'Kitchen Countertop Stove 03',
    thumbnail: '/items/kitchen-countertop-stove-03/thumbnail.webp',
    src: '/items/kitchen-countertop-stove-03/model.glb',
    dimensions: [2.5, 1, 0.9],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 1 },
  },
  {
    id: 'kitchen-countertop-04',
    category: 'kitchen',
    tags: [
      'floor',
      'kitchen',
      'countertop',
      'counter',
      'worktop',
      'cabinet',
      'stove',
      'cooktop',
      'range',
      'hob',
      'burner',
      'compact',
      'against-wall',
      '厨房台面',
      '操作台',
      '灶台',
      '燃气灶',
    ],
    name: 'Compact Cooktop 04',
    thumbnail: '/items/kitchen-countertop-04/thumbnail.webp',
    src: '/items/kitchen-countertop-04/model.glb',
    dimensions: [0.6, 0.9, 0.6],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.9 },
  },
  {
    id: 'fridge',
    category: 'kitchen',
    tags: ['floor', 'large', 'kitchen'],
    name: 'Fridge',
    thumbnail: '/items/fridge/thumbnail.webp',
    src: '/items/fridge/model.glb',
    dimensions: [0.5954, 1.8424, 0.625],
    offset: [0, 0, -0.0001],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toilet',
    category: 'bathroom',
    tags: ['floor', 'large', 'bathroom'],
    name: 'Toilet',
    thumbnail: '/items/toilet/thumbnail.webp',
    src: '/items/toilet/model.glb',
    dimensions: [0.4349, 0.6461, 0.7214],
    offset: [0.0354, 0.0001, -0.0754],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bathroom-sink',
    category: 'bathroom',
    tags: ['floor', 'large', 'bathroom'],
    name: 'Bathroom Sink',
    thumbnail: '/items/bathroom-sink/thumbnail.webp',
    src: '/items/bathroom-sink/model.glb',
    dimensions: [1.05, 1.1937, 0.59],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shower-square',
    category: 'bathroom',
    tags: ['floor', 'large', 'bathroom'],
    name: 'Squared Shower',
    thumbnail: '/items/shower-square/thumbnail.webp',
    src: '/items/shower-square/model.glb',
    dimensions: [1, 2, 1],
    offset: [0.41, 0, -0.42],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bathtub',
    category: 'bathroom',
    tags: ['floor', 'large', 'bathroom'],
    name: 'Bathtub',
    thumbnail: '/items/bathtub/thumbnail.webp',
    src: '/items/bathtub/model.glb',
    dimensions: [1.9212, 0.5829, 0.84],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'washing-machine',
    category: 'bathroom',
    tags: ['floor', 'large', 'electronics', 'laundry'],
    name: 'Washing Machine',
    thumbnail: '/items/washing-machine/thumbnail.webp',
    src: '/items/washing-machine/model.glb',
    dimensions: [0.6442, 0.9, 0.6196],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'drying-rack',
    category: 'bathroom',
    tags: ['floor', 'laundry'],
    name: 'Drying Rack',
    thumbnail: '/items/drying-rack/thumbnail.webp',
    src: '/items/drying-rack/model.glb',
    dimensions: [2, 1.1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'coat-rack',
    category: 'furniture',
    tags: ['floor', 'storage', 'entry'],
    name: 'Coat Rack',
    thumbnail: '/items/coat-rack/thumbnail.webp',
    src: '/items/coat-rack/model.glb',
    dimensions: [0.5, 1.8, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toilet-compact',
    category: 'bathroom',
    tags: ['floor', 'bathroom', 'compact'],
    name: 'Compact Toilet',
    thumbnail: '/items/toilet-compact/thumbnail.webp',
    src: '/items/toilet-compact/model.glb',
    dimensions: [0.4221, 0.5126, 0.6681],
    offset: [0.0084, 0.0026, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'closet-large',
    category: 'furniture',
    tags: ['floor', 'storage', 'bedroom', 'large', 'wardrobe'],
    name: 'Large Closet',
    thumbnail: '/items/closet-large/thumbnail.webp',
    src: '/items/closet-large/model.glb',
    dimensions: [1.821, 2.4, 0.6],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fridge-wide',
    category: 'kitchen',
    tags: ['floor', 'large', 'kitchen', 'wide', 'refrigerator'],
    name: 'Wide Fridge',
    thumbnail: '/items/fridge-wide/thumbnail.webp',
    src: '/items/fridge-wide/model.glb',
    dimensions: [0.889, 1.778, 0.8636],
    offset: [0, 0, -0.0254],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fridge-compact',
    category: 'kitchen',
    tags: ['floor', 'kitchen', 'compact', 'refrigerator'],
    name: 'Compact Fridge',
    thumbnail: '/items/fridge-compact/thumbnail.webp',
    src: '/items/fridge-compact/model.glb',
    dimensions: [0.5048, 0.8334, 0.5223],
    offset: [0, 0.0032, -0.0008],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'single-bed-high',
    category: 'furniture',
    tags: ['floor', 'bedroom', 'bed', 'single', 'high'],
    name: 'High Single Bed',
    thumbnail: '/items/single-bed-high/thumbnail.webp',
    src: '/items/single-bed-high/model.glb',
    dimensions: [1.0994, 1.239, 1.9851],
    offset: [0.0132, 0, -0.0109],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'single-bed-standard',
    category: 'furniture',
    tags: ['floor', 'bedroom', 'bed', 'single', 'standard'],
    name: 'Standard Single Bed',
    thumbnail: '/items/single-bed-standard/thumbnail.webp',
    src: '/items/single-bed-standard/model.glb',
    dimensions: [1.06, 0.77, 2.1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'double-bed-compact',
    category: 'furniture',
    tags: ['floor', 'bedroom', 'bed', 'double', 'compact'],
    name: 'Compact Double Bed',
    thumbnail: '/items/double-bed-compact/thumbnail.webp',
    src: '/items/double-bed-compact/model.glb',
    dimensions: [1.1104, 1.003, 2],
    offset: [0, 0, -0.0052],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'desk-wide',
    category: 'furniture',
    tags: ['floor', 'table', 'office', 'study', 'desk', 'wide'],
    name: 'Wide Desk',
    thumbnail: '/items/desk-wide/thumbnail.webp',
    src: '/items/desk-wide/model.glb',
    dimensions: [1.4192, 0.7493, 0.4985],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.7493 },
  },
  {
    id: 'desk-deep',
    category: 'furniture',
    tags: ['floor', 'table', 'office', 'study', 'desk', 'deep'],
    name: 'Deep Desk',
    thumbnail: '/items/desk-deep/thumbnail.webp',
    src: '/items/desk-deep/model.glb',
    dimensions: [1.36, 0.7243, 0.68],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.7243 },
  },
  {
    id: 'dining-chair-classic',
    category: 'furniture',
    tags: ['floor', 'seating', 'dining', 'chair', 'classic'],
    name: 'Classic Dining Chair',
    thumbnail: '/items/dining-chair-classic/thumbnail.webp',
    src: '/items/dining-chair-classic/model.glb',
    dimensions: [0.45, 0.9067, 0.47],
    offset: [0, 0.0028, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'armchair',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'chair', 'armchair'],
    name: 'Armchair',
    thumbnail: '/items/armchair/thumbnail.webp',
    src: '/items/armchair/model.glb',
    dimensions: [0.6399, 0.9149, 0.6314],
    offset: [0.0006, 0, -0.0034],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'chair-compact',
    category: 'furniture',
    tags: ['floor', 'seating', 'dining', 'chair', 'compact'],
    name: 'Compact Chair',
    thumbnail: '/items/chair-compact/thumbnail.webp',
    src: '/items/chair-compact/model.glb',
    dimensions: [0.4396, 0.7481, 0.5389],
    offset: [0, 0.0007, 0.0003],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa-two-seat-modern',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'sofa', 'two-seat', 'modern'],
    name: 'Modern Two Seat Sofa',
    thumbnail: '/items/sofa-two-seat-modern/thumbnail.webp',
    src: '/items/sofa-two-seat-modern/model.glb',
    dimensions: [2.0308, 0.7427, 0.8548],
    offset: [0, 0, -0.0136],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa-large',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'sofa', 'large', 'three-seat'],
    name: 'Large Sofa',
    thumbnail: '/items/sofa-large/thumbnail.webp',
    src: '/items/sofa-large/model.glb',
    dimensions: [2.3171, 0.8431, 0.8941],
    offset: [0, 0, 0.0088],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa-single-compact',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'sofa', 'single-seat', 'compact'],
    name: 'Compact Single Seat Sofa',
    thumbnail: '/items/sofa-single-compact/thumbnail.webp',
    src: '/items/sofa-single-compact/model.glb',
    dimensions: [0.7685, 0.6951, 0.7238],
    offset: [0, 0, 0.003],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bathroom-sink-compact',
    category: 'bathroom',
    tags: ['floor', 'bathroom', 'sink', 'compact'],
    name: 'Compact Bathroom Sink',
    thumbnail: '/items/bathroom-sink-compact/thumbnail.webp',
    src: '/items/bathroom-sink-compact/model.glb',
    dimensions: [0.6, 1.3072, 0.6148],
    offset: [0, 0, -0.0074],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bench-upholstered',
    category: 'furniture',
    tags: ['floor', 'seating', 'living', 'bench', 'upholstered'],
    name: 'Upholstered Bench',
    thumbnail: '/items/bench-upholstered/thumbnail.webp',
    src: '/items/bench-upholstered/model.glb',
    dimensions: [2, 0.86, 0.6053],
    offset: [-0.0004, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bench-compact',
    category: 'furniture',
    tags: ['floor', 'seating', 'entry', 'bench', 'compact'],
    name: 'Compact Bench',
    thumbnail: '/items/bench-compact/thumbnail.webp',
    src: '/items/bench-compact/model.glb',
    dimensions: [1.2, 0.42, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bench-standard',
    category: 'furniture',
    tags: ['floor', 'seating', 'entry', 'bench', 'standard'],
    name: 'Standard Bench',
    thumbnail: '/items/bench-standard/thumbnail.webp',
    src: '/items/bench-standard/model.glb',
    dimensions: [1.5, 0.45, 0.45],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'dining-table-round',
    category: 'furniture',
    tags: ['floor', 'table', 'dining', 'round', 'compact'],
    name: 'Round Dining Table',
    thumbnail: '/items/dining-table-round/thumbnail.webp',
    src: '/items/dining-table-round/model.glb',
    dimensions: [1, 0.775, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.775 },
  },
  {
    id: 'bathroom-vanity-compact',
    category: 'bathroom',
    tags: ['floor', 'bathroom', 'vanity', 'sink', 'storage', 'compact'],
    name: 'Compact Bathroom Vanity',
    thumbnail: '/items/bathroom-vanity-compact/thumbnail.webp',
    src: '/items/bathroom-vanity-compact/model.glb',
    dimensions: [0.45, 0.9163, 0.42],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.9163 },
  },
  {
    id: 'kitchen-wall-cabinet',
    category: 'kitchen',
    tags: ['floor', 'kitchen', 'cabinet', 'storage', 'against-wall'],
    name: 'Kitchen Wall Cabinet',
    thumbnail: '/items/kitchen-wall-cabinet/thumbnail.webp',
    src: '/items/kitchen-wall-cabinet/model.glb',
    dimensions: [1.3453, 0.76, 0.373],
    offset: [-0.0032, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.76 },
  },
  {
    id: 'shoe-cabinet',
    category: 'furniture',
    tags: ['floor', 'entry', 'storage', 'shoe', 'cabinet', 'compact'],
    name: 'Shoe Cabinet',
    thumbnail: '/items/shoe-cabinet/thumbnail.webp',
    src: '/items/shoe-cabinet/model.glb',
    dimensions: [0.6, 1.1, 0.2319],
    offset: [0, 0, -0.016],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 1.1 },
  },
  {
    id: 'kitchen-sink-counter',
    category: 'kitchen',
    tags: ['floor', 'kitchen', 'sink', 'counter', 'cabinet', 'storage'],
    name: 'Kitchen Sink Counter',
    thumbnail: '/items/kitchen-sink-counter/thumbnail.webp',
    src: '/items/kitchen-sink-counter/model.glb',
    dimensions: [1.55, 1.0955, 0.6],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 1.0955 },
  },

  // --- Synced from packages/editor's larger catalog (packages/editor/src/components/ui/item-catalog/catalog-items.tsx) ---
  // 85 additional items added to close obvious gaps (desks, office chairs, lighting,
  // plants/decor, rugs, more appliances) in the original 23-item headless subset.
  // Hosted on the same Supabase CDN the editor already uses, so no new asset
  // deployment is required. IDs that already existed above were skipped to avoid
  // duplicates. The 'interactive' field (light/animation UI controls) was dropped as
  // irrelevant to headless placement. Two user-uploaded/community items (dishwasher,
  // fireplace) were excluded, keeping only curated 'system' library assets.
  {
    id: 'cactus',
    category: 'furniture',
    tags: [
      'cactus',
      'rack',
      'stand',
      'hanger',
      'sculpture',
      'decor',
      'modern',
      'contemporary',
      'pop',
      'green',
      'organizer',
      'storage',
      'sculptural',
    ],
    name: 'Cactus',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cactus/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cactus/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cactus/floor-plan.png',
    dimensions: [0.34, 0.39, 0.27],
    offset: [-0.0039, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'dining-table-mo9ms5yh',
    category: 'furniture',
    tags: [
      'dining',
      'table',
      'dinette',
      'wood',
      'oak',
      'modern',
      'minimalist',
      'scandinavian',
      'rectangular',
      'kitchen',
      'mealtime',
      'entertaining',
    ],
    name: 'Dining table',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-table-mo9ms5yh/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-table-mo9ms5yh/models/item_model_Sffq4hIGw8R3keLh.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-table-mo9ms5yh/floor-plan.png',
    dimensions: [2, 0.77, 0.91],
    offset: [0.0002, 0.3793, -0.0026],
    rotation: [0, 0, 0],
    scale: [2, 2, 2],
    surface: { height: 0.77 },
  },
  {
    id: 'small-indoor-plant',
    category: 'furniture',
    tags: ['countertop', 'decor', 'vegetation'],
    name: 'Small Plant',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/small-indoor-plant/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/small-indoor-plant/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/small-indoor-plant/floor-plan.png',
    dimensions: [0.4, 0.67, 0.38],
    offset: [-0.0106, 0, 0.0067],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'column',
    category: 'furniture',
    tags: [
      'column',
      'pillar',
      'pedestal',
      'plinth',
      'stand',
      'marble',
      'stone',
      'classical',
      'roman',
      'greek',
      'decorative',
      'architectural',
      'antique',
      'support',
      'base',
    ],
    name: 'Column',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/column/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/column/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/column/floor-plan.png',
    dimensions: [0.5, 2.5, 0.5],
    offset: [0, 1.25, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'barbell',
    category: 'furniture',
    tags: [
      'barbell',
      'weight',
      'steel',
      'iron',
      'metal',
      'gym',
      'fitness',
      'industrial',
      'workout',
      'strength',
      'training',
      'lifting',
      'chrome',
      'exercise',
    ],
    name: 'Barbell',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell/floor-plan.png',
    dimensions: [0.38, 0.38, 1.72],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toy',
    category: 'furniture',
    tags: ['floor', 'kids', 'decor'],
    name: 'Toy',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toy/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toy/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toy/floor-plan.png',
    dimensions: [0.29, 0.49, 0.34],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'barbell-stand',
    category: 'furniture',
    tags: [
      'rack',
      'stand',
      'holder',
      'storage',
      'metal',
      'steel',
      'industrial',
      'fitness',
      'gym',
      'weightlifting',
      'training',
      'minimalist',
      'black',
      'organizer',
    ],
    name: 'Barbell Stand',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell-stand/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell-stand/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell-stand/floor-plan.png',
    dimensions: [1.34, 1.22, 1.72],
    offset: [-0.0173, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'books',
    category: 'furniture',
    tags: [
      'books',
      'novels',
      'literature',
      'reading',
      'vintage',
      'classic',
      'decorative',
      'paper',
      'leather',
      'library',
      'study',
      'office',
      'decor',
      'shelf',
      'antique',
    ],
    name: 'Books',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/books/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/books/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/books/floor-plan.png',
    dimensions: [0.22, 0.22, 0.18],
    offset: [-0.0851, 0.003, 0.0209],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'stool',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Stool',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stool/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stool/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stool/floor-plan.png',
    dimensions: [0.52, 1.16, 0.55],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'pool-table',
    category: 'furniture',
    tags: [
      'pool',
      'billiards',
      'snooker',
      'table',
      'recreation',
      'leisure',
      'entertainment',
      'wood',
      'felt',
      'gaming',
      'traditional',
      'luxury',
      'classic',
      'hobby',
      'furniture',
    ],
    name: 'Pool table',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pool-table/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pool-table/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pool-table/floor-plan.png',
    dimensions: [2.11, 0.98, 3.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bookshelf',
    category: 'furniture',
    tags: [
      'bookshelf',
      'bookcase',
      'shelving',
      'storage',
      'organizer',
      'modern',
      'minimalist',
      'wood',
      'metal',
      'industrial',
      'library',
      'office',
      'furniture',
      'display',
      'timber',
    ],
    name: 'Bookshelf',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bookshelf/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bookshelf/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bookshelf/floor-plan.png',
    dimensions: [0.93, 1.99, 0.33],
    offset: [0, 0, 0.0032],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'car-toy',
    category: 'furniture',
    tags: [
      'car',
      'toy',
      'vehicle',
      'racer',
      'play',
      'nursery',
      'playroom',
      'wooden',
      'vintage',
      'decor',
      'kids',
      'child',
      'classic',
      'miniature',
      'hobby',
    ],
    name: 'Car Toy',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/car-toy/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/car-toy/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/car-toy/floor-plan.png',
    dimensions: [0.31, 0.38, 0.6],
    offset: [0.0005, 0.0005, -0.0075],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bunkbed',
    category: 'furniture',
    tags: [
      'bunkbed',
      'bed',
      'sleeper',
      'loft',
      'bedroom',
      'kids',
      'wood',
      'metal',
      'modern',
      'sleeping',
      'ladder',
      'rustic',
      'dormitory',
      'furniture',
    ],
    name: 'Bunkbed',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bunkbed/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bunkbed/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bunkbed/floor-plan.png',
    dimensions: [1.65, 1.55, 0.99],
    offset: [0, 0, -0.0886],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'my-leather-couch-modp80ha',
    category: 'furniture',
    name: 'My leather couch',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/my-leather-couch-modp80ha/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/my-leather-couch-modp80ha/models/item_model_kgORhH5vwFK8xub0.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/my-leather-couch-modp80ha/floor-plan.png',
    dimensions: [2, 0.67, 0.61],
    offset: [-0.0005, 0.3228, -0.004],
    rotation: [0, 0, 0],
    scale: [2, 2, 2],
  },
  {
    id: 'office-table',
    category: 'furniture',
    tags: [
      'desk',
      'table',
      'workstation',
      'furniture',
      'office',
      'work',
      'study',
      'writing',
      'modern',
      'minimalist',
      'industrial',
      'wood',
      'metal',
    ],
    name: 'Office Table',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/office-table/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/office-table/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/office-table/floor-plan.png',
    dimensions: [1.51, 0.76, 0.62],
    offset: [-0.0001, 0, -0.0052],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.75 },
  },
  {
    id: 'guitar',
    category: 'furniture',
    tags: [
      'guitar',
      'instrument',
      'musical',
      'wood',
      'acoustic',
      'vintage',
      'classic',
      'decor',
      'mahogany',
      'string',
      'art',
      'hobby',
    ],
    name: 'Guitar',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/guitar/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/guitar/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/guitar/floor-plan.png',
    dimensions: [0.4, 1.18, 0.09],
    offset: [-0.0009, 0.3197, -0.0129],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'trash-bin',
    category: 'furniture',
    tags: ['floor'],
    name: 'Trash Bin',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/trash-bin/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/trash-bin/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/trash-bin/floor-plan.png',
    dimensions: [0.35, 0.59, 0.42],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'recessed-light',
    category: 'furniture',
    tags: [
      'recessed',
      'downlight',
      'spotlight',
      'lighting',
      'fixture',
      'modern',
      'minimalist',
      'metal',
      'aluminum',
      'luminaire',
      'ambient',
      'illumination',
      'architectural',
      'can',
    ],
    name: 'Recessed Light',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/recessed-light/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/recessed-light/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/recessed-light/floor-plan.png',
    dimensions: [0.23, 0.06, 0.23],
    offset: [0, 0.0057, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
  },
  {
    id: 'table-lamp',
    category: 'furniture',
    tags: ['countertop', 'lighting'],
    name: 'Table Lamp',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/table-lamp/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/table-lamp/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/table-lamp/floor-plan.png',
    dimensions: [0.29, 0.74, 0.67],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ceiling-lamp',
    category: 'furniture',
    tags: [
      'lamp',
      'light',
      'chandelier',
      'pendant',
      'luminaire',
      'fixture',
      'lighting',
      'modern',
      'minimalist',
      'glass',
      'metal',
      'indoor',
      'illumination',
      'interior',
    ],
    name: 'Ceiling Lamp',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ceiling-lamp/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ceiling-lamp/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ceiling-lamp/floor-plan.png',
    dimensions: [0.55, 0.86, 0.55],
    offset: [0, 0.8545, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
  },
  {
    id: 'ikea-kallax-1x4-moa2y49n',
    category: 'furniture',
    tags: [
      'shelf',
      'bookcase',
      'shelving',
      'storage',
      'organizer',
      'cubby',
      'cube',
      'scandinavian',
      'modern',
      'minimalist',
      'wood',
      'laminate',
      'display',
      'modular',
    ],
    name: 'Ikea Kallax 2x4',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ikea-kallax-1x4-moa2y49n/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ikea-kallax-1x4-moa2y49n/models/item_model_ocVHS1SWDex5DeYc.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ikea-kallax-1x4-moa2y49n/floor-plan.png',
    dimensions: [1.09, 2.06, 0.55],
    offset: [0, -0.0053, 0],
    rotation: [0, 0, 0],
    scale: [1.4, 1.4, 1.4],
  },
  {
    id: 'indoor-plant',
    category: 'furniture',
    tags: [
      'plant',
      'greenery',
      'botanical',
      'foliage',
      'houseplant',
      'organic',
      'natural',
      'modern',
      'minimalist',
      'tropical',
      'decor',
      'accent',
      'green',
      'ceramic',
    ],
    name: 'Indoor Plant',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/indoor-plant/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/indoor-plant/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/indoor-plant/floor-plan.png',
    dimensions: [0.69, 1.63, 0.83],
    offset: [-0.0506, 0, 0.0664],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ironing-board',
    category: 'furniture',
    tags: [
      'ironing',
      'board',
      'laundry',
      'foldable',
      'metal',
      'utility',
      'pressing',
      'collapsible',
      'stand',
      'table',
      'organization',
      'industrial',
    ],
    name: 'Ironing Board',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ironing-board/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ironing-board/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ironing-board/floor-plan.png',
    dimensions: [1.31, 0.96, 0.48],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'floor-lamp',
    category: 'furniture',
    tags: [
      'lamp',
      'luminaire',
      'light',
      'torchere',
      'lighting',
      'illumination',
      'metal',
      'brass',
      'modern',
      'minimalist',
      'industrial',
      'decor',
      'ambient',
      'reading',
      'sleek',
    ],
    name: 'Floor Lamp',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/floor-lamp/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/floor-lamp/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/floor-lamp/floor-plan.png',
    dimensions: [0.7, 1.86, 0.69],
    offset: [0.0341, 0.0045, 0.0219],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'herman-miller-aeron-mo8x36k9',
    category: 'furniture',
    tags: ['office'],
    name: 'Herman Miller Aeron',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/herman-miller-aeron-mo8x36k9/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/herman-miller-aeron-mo8x36k9/models/item_model_YshL4maC8cHtry5c.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/herman-miller-aeron-mo8x36k9/floor-plan.png',
    dimensions: [0.67, 1.06, 0.66],
    offset: [-0.0013, 0.5256, 0.0028],
    rotation: [0, 0, 0],
    scale: [1.05, 1.05, 1.05],
  },
  {
    id: 'easel',
    category: 'furniture',
    tags: [
      'easel',
      'stand',
      'tripod',
      'art',
      'studio',
      'wood',
      'display',
      'canvas',
      'atelier',
      'presentation',
      'wooden',
      'sketching',
      'painting',
      'decor',
    ],
    name: 'Easel',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/easel/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/easel/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/easel/floor-plan.png',
    dimensions: [0.99, 2.32, 0.55],
    offset: [0, 0.0402, 0.0116],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'lounge-chair',
    category: 'furniture',
    tags: [
      'chair',
      'armchair',
      'seating',
      'lounge',
      'seat',
      'modern',
      'contemporary',
      'minimalist',
      'comfort',
      'relaxation',
      'upholstered',
      'interior',
      'furniture',
    ],
    name: 'Lounge Chair',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/lounge-chair/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/lounge-chair/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/lounge-chair/floor-plan.png',
    dimensions: [0.68, 1.03, 1.26],
    offset: [0, 0.0034, 0.0894],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'office-chair',
    category: 'furniture',
    tags: [
      'chair',
      'seating',
      'ergonomic',
      'swivel',
      'office',
      'desk',
      'mesh',
      'leather',
      'modern',
      'task',
      'workspace',
      'professional',
      'computer',
    ],
    name: 'Office Chair',
    thumbnail: '/items/office-chair/thumbnail.webp',
    src: '/items/office-chair/model.glb',
    dimensions: [0.7121, 1.2196, 0.6895],
    offset: [0.0017, 0.0001, 0.0273],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'piano',
    category: 'furniture',
    tags: [
      'piano',
      'instrument',
      'musical',
      'grand',
      'upright',
      'keyboard',
      'wood',
      'polished',
      'lacquer',
      'ebony',
      'classic',
      'traditional',
      'music',
      'entertainment',
      'luxury',
    ],
    name: 'Piano',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/piano/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/piano/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/piano/floor-plan.png',
    dimensions: [1.54, 1.44, 0.69],
    offset: [0, 0, 0.0162],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'picture',
    category: 'furniture',
    tags: [
      'picture',
      'frame',
      'art',
      'artwork',
      'print',
      'canvas',
      'decor',
      'modern',
      'abstract',
      'minimalist',
      'decorative',
      'glass',
      'wood',
      'illustration',
      'portrait',
    ],
    name: 'Picture',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/picture/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/picture/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/picture/floor-plan.png',
    dimensions: [1.47, 0.82, 0.06],
    offset: [0, 0.41, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'rectangular-carpet',
    category: 'furniture',
    tags: [
      'carpet',
      'rug',
      'mat',
      'textile',
      'woven',
      'rectangular',
      'modern',
      'wool',
      'cotton',
      'minimalist',
      'decor',
      'plush',
    ],
    name: 'Rectangular Carpet',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/rectangular-carpet/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/rectangular-carpet/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/rectangular-carpet/floor-plan.png',
    dimensions: [2.78, 0.04, 1.81],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.03 },
  },
  {
    id: 'round-mirror',
    category: 'furniture',
    tags: [
      'mirror',
      'glass',
      'reflective',
      'circular',
      'oval',
      'modern',
      'minimalist',
      'contemporary',
      'scandinavian',
      'vanity',
      'decor',
      'curved',
      'reflection',
      'grooming',
    ],
    name: 'Rounded Mirror',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/round-mirror/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/round-mirror/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/round-mirror/floor-plan.png',
    dimensions: [0.57, 0.57, 0.05],
    offset: [0, 0.2848, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'round-carpet',
    category: 'furniture',
    tags: [
      'carpet',
      'rug',
      'mat',
      'circular',
      'modern',
      'minimalist',
      'scandinavian',
      'textile',
      'woven',
      'decor',
      'accent',
      'wool',
      'fiber',
      'interior',
    ],
    name: 'Round Carpet',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/round-carpet/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/round-carpet/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/round-carpet/floor-plan.png',
    dimensions: [1.99, 0.05, 1.99],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.04 },
  },
  {
    id: 'threadmill',
    category: 'furniture',
    tags: ['floor', 'fitness'],
    name: 'Threadmill',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/threadmill/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/threadmill/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/threadmill/floor-plan.png',
    dimensions: [2.1, 1.45, 0.9],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'standing-desk-mo8wgz95',
    category: 'furniture',
    tags: ['office'],
    name: 'Standing Desk',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/standing-desk-mo8wgz95/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/standing-desk-mo8wgz95/models/item_model_zzZ58018waP8VY6Z.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/standing-desk-mo8wgz95/floor-plan.png',
    dimensions: [1.41, 0.85, 0.68],
    offset: [0, 0.4203, 0.0019],
    rotation: [0, 0, 0],
    scale: [1.4, 1.4, 1.4],
  },
  {
    id: 'sprinkler',
    category: 'appliance',
    tags: ['ceiling', 'safety'],
    name: 'Sprinkler',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sprinkler/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sprinkler/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sprinkler/floor-plan.png',
    dimensions: [0.09, 0.04, 0.09],
    offset: [0, 0.0386, 0],
    rotation: [3.141592653589793, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
  },
  {
    id: 'exit-sign',
    category: 'appliance',
    tags: [
      'sign',
      'signage',
      'exit',
      'emergency',
      'safety',
      'wayfinding',
      'directional',
      'lighting',
      'led',
      'commercial',
      'industrial',
      'marker',
      'egress',
      'appliance',
    ],
    name: 'Exit Sign',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/exit-sign/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/exit-sign/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/exit-sign/floor-plan.png',
    dimensions: [0.54, 0.27, 0.1],
    offset: [0, 0.0036, 0.0452],
    rotation: [0, 0, 0],
    scale: [0.6, 0.5, 0.7],
    attachTo: 'wall-side',
  },
  {
    id: 'sewing-machine',
    category: 'appliance',
    tags: [
      'sewing',
      'machine',
      'appliance',
      'tailor',
      'craft',
      'hobby',
      'textile',
      'metal',
      'plastic',
      'vintage',
      'modern',
      'industrial',
      'mending',
      'stitching',
    ],
    name: 'Sewing Machine',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sewing-machine/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sewing-machine/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sewing-machine/floor-plan.png',
    dimensions: [0.83, 0.68, 0.32],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'television',
    category: 'appliance',
    tags: ['floor', 'electronics'],
    name: 'Television',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/television/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/television/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/television/floor-plan.png',
    dimensions: [1.62, 1.07, 0.38],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'power-outlet-moa09g0o',
    category: 'appliance',
    tags: ['electric'],
    name: 'Power Outlet',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/power-outlet-moa09g0o/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/power-outlet-moa09g0o/models/item_model_PTDhACPTrrrtLLeI.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/power-outlet-moa09g0o/floor-plan.png',
    dimensions: [0.09, 0.09, 0.03],
    offset: [0, 0.045, 0.0117],
    rotation: [0, 0, 0],
    scale: [0.09, 0.09, 0.09],
    attachTo: 'wall-side',
  },
  {
    id: 'ac-block',
    category: 'appliance',
    tags: [
      'conditioner',
      'cooler',
      'hvac',
      'cooling',
      'appliance',
      'vent',
      'modern',
      'minimalist',
      'metal',
      'industrial',
      'white',
      'utility',
      'ventilation',
      'unit',
      'climate',
    ],
    name: 'AC block',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ac-block/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ac-block/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ac-block/floor-plan.png',
    dimensions: [1.06, 0.95, 1.06],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [0.79, 0.79, 0.79],
  },
  {
    id: 'stereo-speaker',
    category: 'appliance',
    tags: ['floor', 'electronics'],
    name: 'Stereo Speaker',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stereo-speaker/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stereo-speaker/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stereo-speaker/floor-plan.png',
    dimensions: [0.23, 1, 0.34],
    offset: [0, 0, -0.0129],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'thermostat',
    category: 'appliance',
    tags: ['wall', 'climate', 'electrical'],
    name: 'Thermostat',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/thermostat/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/thermostat/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/thermostat/floor-plan.png',
    dimensions: [0.1, 0.1, 0.01],
    offset: [0, 0.0013, 0.0022],
    rotation: [0, 0, 0],
    scale: [2.08, 2.1, 2.59],
    attachTo: 'wall-side',
  },
  {
    id: 'toaster',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Toaster',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toaster/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toaster/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toaster/floor-plan.png',
    dimensions: [0.28, 0.23, 0.17],
    offset: [-0.0057, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kettle',
    category: 'appliance',
    tags: [
      'kettle',
      'teapot',
      'boiler',
      'electric',
      'kitchen',
      'appliance',
      'metal',
      'steel',
      'modern',
      'tea',
      'coffee',
      'boiling',
      'beverage',
      'breakfast',
    ],
    name: 'Kettle',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kettle/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kettle/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kettle/floor-plan.png',
    dimensions: [0.24, 0.25, 0.18],
    offset: [-0.026, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'hydrant',
    category: 'appliance',
    tags: [
      'hydrant',
      'faucet',
      'spigot',
      'valve',
      'metal',
      'iron',
      'industrial',
      'vintage',
      'retro',
      'plumbing',
      'water',
      'utility',
      'outdoor',
      'garden',
      'red',
    ],
    name: 'Hydrant',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hydrant/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hydrant/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hydrant/floor-plan.png',
    dimensions: [0.64, 0.88, 0.64],
    offset: [-0.0046, 0, -0.0008],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fire-detector',
    category: 'appliance',
    tags: [
      'detector',
      'alarm',
      'sensor',
      'smoke',
      'alert',
      'safety',
      'security',
      'protection',
      'appliance',
      'white',
      'plastic',
      'minimalist',
      'modern',
      'warning',
      'electronic',
    ],
    name: 'Fire Detector',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fire-detector/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fire-detector/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fire-detector/floor-plan.png',
    dimensions: [0.12, 0.19, 0.07],
    offset: [0.0281, 0.012, 0.0015],
    rotation: [0, 0, 0],
    scale: [0.9, 1.4, 0.7],
    attachTo: 'wall',
  },
  {
    id: 'smoke-detector',
    category: 'appliance',
    tags: ['ceiling', 'safety'],
    name: 'Smoke Detector',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/smoke-detector/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/smoke-detector/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/smoke-detector/floor-plan.png',
    dimensions: [0.16, 0.05, 0.16],
    offset: [0, 0.0492, 0],
    rotation: [3.141592653589793, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
  },
  {
    id: 'coffee-machine',
    category: 'appliance',
    tags: [
      'coffee',
      'machine',
      'maker',
      'espresso',
      'brewer',
      'kitchen',
      'appliance',
      'modern',
      'metal',
      'sleek',
      'black',
      'silver',
      'beverage',
      'brewing',
    ],
    name: 'Coffee Machine',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/coffee-machine/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/coffee-machine/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/coffee-machine/floor-plan.png',
    dimensions: [0.16, 0.24, 0.23],
    offset: [0.0003, 0.0003, -0.0366],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ceiling-fan',
    category: 'appliance',
    tags: [
      'fan',
      'ventilator',
      'cooling',
      'airflow',
      'blades',
      'modern',
      'industrial',
      'metal',
      'wood',
      'appliance',
      'ventilation',
      'breeze',
      'climate',
      'circulation',
    ],
    name: 'Ceiling fan',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ceiling-fan/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ceiling-fan/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ceiling-fan/floor-plan.png',
    dimensions: [0.92, 0.35, 1.04],
    offset: [-0.1371, 0.3448, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
  },
  {
    id: 'iron',
    category: 'appliance',
    tags: [
      'iron',
      'steamer',
      'laundry',
      'clothing',
      'modern',
      'metal',
      'plastic',
      'ceramic',
      'garment',
      'pressing',
      'household',
      'utility',
      'appliance',
      'sleek',
    ],
    name: 'Iron',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/iron/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/iron/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/iron/floor-plan.png',
    dimensions: [0.36, 0.24, 0.21],
    offset: [0.026, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'air-conditioning',
    category: 'appliance',
    tags: [
      'conditioner',
      'cooling',
      'hvac',
      'appliance',
      'electronic',
      'modern',
      'minimalist',
      'white',
      'climate',
      'temperature',
      'ventilation',
      'airflow',
      'comfort',
      'sleek',
    ],
    name: 'Air Conditioning',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/air-conditioning/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/air-conditioning/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/air-conditioning/floor-plan.png',
    dimensions: [1.56, 0.6, 0.41],
    offset: [0, 0.3, 0.2018],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'computer',
    category: 'appliance',
    tags: [
      'computer',
      'desktop',
      'workstation',
      'monitor',
      'technology',
      'office',
      'electronics',
      'modern',
      'sleek',
      'metal',
      'silver',
      'minimalist',
      'hardware',
      'productivity',
    ],
    name: 'Computer',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/computer/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/computer/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/computer/floor-plan.png',
    dimensions: [0.68, 0.48, 0.19],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'alarm-keypad',
    category: 'appliance',
    tags: [
      'alarm',
      'keypad',
      'panel',
      'security',
      'interface',
      'controller',
      'modern',
      'minimalist',
      'digital',
      'plastic',
      'white',
      'electronic',
      'safety',
      'automation',
      'smart',
    ],
    name: 'Alarm Keypad',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/alarm-keypad/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/alarm-keypad/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/alarm-keypad/floor-plan.png',
    dimensions: [0.18, 0.13, 0.03],
    offset: [0, 0.0671, -0.0002],
    rotation: [1.5708, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'ev-wall-charger',
    category: 'appliance',
    tags: [
      'charger',
      'station',
      'electric',
      'vehicle',
      'automotive',
      'garage',
      'modern',
      'minimalist',
      'power',
      'energy',
      'appliance',
      'tech',
      'sleek',
      'plastic',
      'black',
    ],
    name: 'Ev-wall-charger',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ev-wall-charger/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ev-wall-charger/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ev-wall-charger/floor-plan.png',
    dimensions: [0.29, 0.65, 0.17],
    offset: [-0.0677, 0.2979, 0.1503],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
  {
    id: 'electric-panel',
    category: 'appliance',
    tags: [
      'breaker',
      'box',
      'fusebox',
      'electrical',
      'utility',
      'industrial',
      'metal',
      'steel',
      'power',
      'circuit',
      'technical',
      'maintenance',
      'energy',
      'appliance',
    ],
    name: 'Electric Panel',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/electric-panel/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/electric-panel/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/electric-panel/floor-plan.png',
    dimensions: [0.4, 0.98, 0.11],
    offset: [0, 0.0036, 0.0611],
    rotation: [0, 0, 0],
    scale: [0.61, 0.74, 0.7],
    attachTo: 'wall-side',
  },
  {
    id: 'shower-angle',
    category: 'bathroom',
    tags: [
      'shower',
      'enclosure',
      'cubicle',
      'modern',
      'glass',
      'corner',
      'bathroom',
      'chrome',
      'minimalist',
      'washing',
      'hygiene',
      'plumbing',
      'stall',
      'sleek',
    ],
    name: 'Angle Shower',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-angle/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-angle/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-angle/floor-plan.png',
    dimensions: [0.83, 1.81, 0.83],
    offset: [0.4102, 0, -0.4102],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toilet-paper',
    category: 'bathroom',
    tags: ['wall', 'decor'],
    name: 'Toilet Paper',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toilet-paper/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toilet-paper/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toilet-paper/floor-plan.png',
    dimensions: [0.26, 0.27, 0.24],
    offset: [0, 0.145, 0.1147],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'shower-rug',
    category: 'bathroom',
    tags: [
      'rug',
      'mat',
      'bathmat',
      'absorbent',
      'cotton',
      'chenille',
      'modern',
      'soft',
      'minimalist',
      'spa',
      'bathroom',
      'hygiene',
      'plush',
      'microfiber',
      'woven',
    ],
    name: 'Shower Rug',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-rug/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-rug/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-rug/floor-plan.png',
    dimensions: [0.77, 0.03, 0.48],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.03 },
  },
  {
    id: 'laundry-bag',
    category: 'bathroom',
    tags: [
      'laundry',
      'bag',
      'hamper',
      'basket',
      'canvas',
      'fabric',
      'storage',
      'organization',
      'modern',
      'minimalist',
      'utility',
      'cleaning',
      'linen',
    ],
    name: 'Laundry Bag',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/laundry-bag/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/laundry-bag/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/laundry-bag/floor-plan.png',
    dimensions: [0.46, 0.78, 0.48],
    offset: [0, 0, -0.0006],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'microwave',
    category: 'kitchen',
    tags: [
      'microwave',
      'oven',
      'appliance',
      'kitchen',
      'cooking',
      'heating',
      'metal',
      'steel',
      'modern',
      'sleek',
      'black',
      'silver',
      'electronics',
      'glass',
      'contemporary',
    ],
    name: 'Microwave',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/microwave/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/microwave/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/microwave/floor-plan.png',
    dimensions: [0.52, 0.27, 0.41],
    offset: [0, 0, -0.0225],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'cutting-board',
    category: 'kitchen',
    tags: [
      'board',
      'wood',
      'kitchen',
      'prep',
      'chopping',
      'serving',
      'block',
      'rustic',
      'culinary',
      'timber',
      'natural',
      'chef',
      'cooking',
    ],
    name: 'Cutting Board',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cutting-board/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cutting-board/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cutting-board/floor-plan.png',
    dimensions: [0.27, 0.07, 0.41],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-utensils',
    category: 'kitchen',
    tags: [
      'utensils',
      'tools',
      'kitchenware',
      'cooking',
      'prep',
      'steel',
      'silicone',
      'wood',
      'modern',
      'gadgets',
      'accessories',
      'silverware',
      'chef',
      'serving',
      'baking',
    ],
    name: 'Kitchen Utensils',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-utensils/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-utensils/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-utensils/floor-plan.png',
    dimensions: [0.23, 0.49, 0.21],
    offset: [0.0184, 0, 0.0165],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'hood',
    category: 'kitchen',
    tags: [
      'hood',
      'vent',
      'extractor',
      'ventilation',
      'kitchen',
      'cooking',
      'appliance',
      'metal',
      'steel',
      'stainless',
      'modern',
      'sleek',
      'industrial',
      'minimalist',
    ],
    name: 'Hood',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hood/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hood/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hood/floor-plan.png',
    dimensions: [1.21, 0.52, 0.51],
    offset: [0, 0.2718, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'wooden-kitchen-bar-moa2hhh4',
    category: 'kitchen',
    tags: [
      'bar',
      'counter',
      'island',
      'breakfast',
      'modern',
      'contemporary',
      'wood',
      'stone',
      'quartz',
      'seating',
      'dining',
      'prep',
      'entertaining',
    ],
    name: 'Kitchen Bar',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wooden-kitchen-bar-moa2hhh4/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wooden-kitchen-bar-moa2hhh4/models/item_model_c6iR1M2eE2I8k5M3.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wooden-kitchen-bar-moa2hhh4/floor-plan.png',
    dimensions: [2.5, 1.06, 0.96],
    offset: [0.0003, 0.5322, -0.0024],
    rotation: [0, 0, 0],
    scale: [2.49, 2.49, 2.49],
    surface: { height: 1.06 },
  },
  {
    id: 'kitchen-cabinet',
    category: 'kitchen',
    tags: [
      'cabinet',
      'cupboard',
      'storage',
      'kitchen',
      'shaker',
      'pantry',
      'wood',
      'timber',
      'modern',
      'contemporary',
      'minimalist',
      'organization',
    ],
    name: 'Kitchen Cabinet',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-cabinet/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-cabinet/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-cabinet/floor-plan.png',
    dimensions: [1.65, 1.09, 0.77],
    offset: [0, 0.0004, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 1.09 },
  },
  {
    id: 'frying-pan',
    category: 'kitchen',
    tags: [
      'frying',
      'pan',
      'skillet',
      'cookware',
      'kitchen',
      'cooking',
      'metal',
      'steel',
      'nonstick',
      'culinary',
      'modern',
      'chef',
      'stove',
      'utensil',
    ],
    name: 'Frying Pan',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/frying-pan/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/frying-pan/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/frying-pan/floor-plan.png',
    dimensions: [0.36, 0.09, 0.64],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fruits',
    category: 'kitchen',
    tags: [
      'fruit',
      'produce',
      'food',
      'kitchen',
      'dining',
      'centerpiece',
      'tabletop',
      'vibrant',
      'fresh',
      'organic',
      'natural',
      'accessory',
      'decor',
      'colorful',
    ],
    name: 'Fruits',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fruits/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fruits/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fruits/floor-plan.png',
    dimensions: [0.39, 0.27, 0.39],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-shelf',
    category: 'kitchen',
    tags: [
      'shelf',
      'shelving',
      'rack',
      'ledge',
      'storage',
      'organizer',
      'kitchen',
      'pantry',
      'modern',
      'minimalist',
      'industrial',
      'wood',
      'metal',
      'utility',
    ],
    name: 'Kitchen Shelf',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-shelf/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-shelf/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-shelf/floor-plan.png',
    dimensions: [2.21, 0.89, 0.52],
    offset: [-0.0009, 0.4478, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'wine-bottle',
    category: 'kitchen',
    tags: ['countertop', 'decor'],
    name: 'Wine Bottle',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wine-bottle/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wine-bottle/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wine-bottle/floor-plan.png',
    dimensions: [0.38, 0.35, 0.17],
    offset: [-0.0461, 0, 0.0135],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ball',
    category: 'outdoor',
    tags: [
      'ball',
      'sphere',
      'orb',
      'globe',
      'round',
      'modern',
      'minimalist',
      'decor',
      'garden',
      'patio',
      'sculpture',
      'ornament',
      'accent',
      'circular',
      'contemporary',
    ],
    name: 'Ball',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ball/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ball/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ball/floor-plan.png',
    dimensions: [0.24, 0.24, 0.24],
    offset: [-0.0001, 0.1194, -0.0001],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bush',
    category: 'outdoor',
    tags: [
      'bush',
      'shrub',
      'plant',
      'greenery',
      'foliage',
      'hedge',
      'natural',
      'organic',
      'lush',
      'landscaping',
      'garden',
      'yard',
      'botanical',
      'outdoor',
      'decorative',
    ],
    name: 'Bush',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bush/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bush/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bush/floor-plan.png',
    dimensions: [3, 1.04, 1.01],
    offset: [-0.1463, 0.0094, -0.113],
    rotation: [0, 0, 0],
    scale: [0.96, 0.96, 0.96],
  },
  {
    id: 'basket-hoop',
    category: 'outdoor',
    tags: [
      'hoop',
      'basketball',
      'rim',
      'net',
      'goal',
      'sporty',
      'recreation',
      'outdoor',
      'metal',
      'steel',
      'athletic',
      'game',
      'play',
      'leisure',
      'activity',
    ],
    name: 'Basket Hoop',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/basket-hoop/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/basket-hoop/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/basket-hoop/floor-plan.png',
    dimensions: [0.58, 1.78, 0.56],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'parking-spot',
    category: 'outdoor',
    tags: [
      'parking',
      'space',
      'stall',
      'driveway',
      'pavement',
      'asphalt',
      'concrete',
      'urban',
      'industrial',
      'utility',
      'vehicle',
      'outdoor',
    ],
    name: 'Parking Spot',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/parking-spot/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/parking-spot/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/parking-spot/floor-plan.png',
    dimensions: [4.95, 0.12, 2.28],
    offset: [0, 0.0121, 0.015],
    rotation: [0, 0, 0],
    scale: [0.9, 1, 0.78],
    surface: { height: 0.015 },
  },
  {
    id: 'palm',
    category: 'outdoor',
    tags: [
      'palm',
      'tree',
      'plant',
      'tropical',
      'exotic',
      'foliage',
      'greenery',
      'botanical',
      'garden',
      'patio',
      'outdoor',
      'lush',
      'organic',
      'nature',
    ],
    name: 'Palm',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/palm/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/palm/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/palm/floor-plan.png',
    dimensions: [0.525, 4.5, 0.496],
    offset: [0, 0.08, 0],
    rotation: [0, 0, 0],
    scale: [0.37, 0.37, 0.37],
  },
  {
    id: 'sunbed',
    category: 'outdoor',
    tags: ['leisure', 'seating', 'floor'],
    name: 'Sunbed',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sunbed/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sunbed/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sunbed/floor-plan.png',
    dimensions: [0.86, 1.13, 1.01],
    offset: [0, 0.0516, 0.0137],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fir-tree',
    category: 'outdoor',
    tags: [
      'fir',
      'tree',
      'plant',
      'evergreen',
      'conifer',
      'foliage',
      'greenery',
      'natural',
      'garden',
      'outdoor',
      'botanical',
      'rustic',
      'alpine',
      'woodland',
    ],
    name: 'Fir',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fir-tree/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fir-tree/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fir-tree/floor-plan.png',
    dimensions: [0.27, 3, 0.23],
    offset: [0.02, 0.05, -0.06],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tree',
    category: 'outdoor',
    tags: ['vegetation'],
    name: 'Tree',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tree/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tree/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tree/floor-plan.png',
    dimensions: [0.79, 5, 0.85],
    offset: [-0.02, 0.17, -0.04],
    rotation: [0, 0, 0],
    scale: [0.65, 0.65, 0.65],
  },
  {
    id: 'skate',
    category: 'outdoor',
    tags: ['leisure', 'kids', 'floor'],
    name: 'Skate',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/skate/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/skate/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/skate/floor-plan.png',
    dimensions: [0.86, 0.11, 0.2],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: '1967-chevrolet-camaro-moa24wsf',
    category: 'outdoor',
    tags: ['car'],
    name: '1967 Chevrolet Camaro',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/1967-chevrolet-camaro-moa24wsf/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/1967-chevrolet-camaro-moa24wsf/models/item_model_vUIp1N69V9RXLqoJ.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/1967-chevrolet-camaro-moa24wsf/floor-plan.png',
    dimensions: [4.09, 1.22, 1.89],
    offset: [-0.0018, 0.5987, 0.0205],
    rotation: [0, 0, 0],
    scale: [4.09, 4.09, 4.09],
  },
  {
    id: 'outdoor-playhouse',
    category: 'outdoor',
    tags: [
      'playhouse',
      'cottage',
      'cabin',
      'fort',
      'wood',
      'cedar',
      'garden',
      'backyard',
      'kids',
      'children',
      'play',
      'recreation',
      'outdoor',
      'rustic',
      'timber',
    ],
    name: 'Outdoor Playhouse',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/outdoor-playhouse/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/outdoor-playhouse/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/outdoor-playhouse/floor-plan.png',
    dimensions: [0.3, 0.47, 0.72],
    offset: [-0.0062, 0, -0.0268],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'patio-umbrella',
    category: 'outdoor',
    tags: [
      'umbrella',
      'parasol',
      'shade',
      'canopy',
      'sunshade',
      'outdoor',
      'patio',
      'garden',
      'modern',
      'polyester',
      'fabric',
      'aluminum',
      'poolside',
      'protection',
      'summer',
    ],
    name: 'Patio Umbrella',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/patio-umbrella/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/patio-umbrella/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/patio-umbrella/floor-plan.png',
    dimensions: [0.139, 3.603, 0.15],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'pillar',
    category: 'outdoor',
    tags: [
      'pillar',
      'column',
      'pedestal',
      'plinth',
      'stone',
      'concrete',
      'classical',
      'architectural',
      'garden',
      'ornament',
      'decoration',
      'support',
    ],
    name: 'Pillar',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pillar/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pillar/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pillar/floor-plan.png',
    dimensions: [0.34, 1.26, 0.3],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'scooter',
    category: 'outdoor',
    tags: [
      'scooter',
      'kickscooter',
      'transport',
      'mobility',
      'outdoor',
      'wheels',
      'metal',
      'aluminum',
      'modern',
      'sleek',
      'urban',
      'active',
      'travel',
      'ride',
      'commute',
    ],
    name: 'Scooter',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/scooter/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/scooter/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/scooter/floor-plan.png',
    dimensions: [0.85, 0.85, 0.45],
    offset: [0.1127, 0.0017, 0.1744],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tesla',
    category: 'outdoor',
    tags: [
      'tesla',
      'car',
      'vehicle',
      'automobile',
      'electric',
      'modern',
      'minimalist',
      'sleek',
      'metal',
      'glass',
      'luxury',
      'transportation',
      'commuting',
    ],
    name: 'Tesla Model Y',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tesla/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tesla/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tesla/floor-plan.png',
    dimensions: [1.98, 1.62, 4.76],
    offset: [0.0039, -0.0102, -0.0148],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
]

export function findCatalogItem(id: string): AssetInput | undefined {
  return MCP_CATALOG_ITEMS.find((item) => item.id === id)
}

export function searchCatalogItems(args: {
  query: string
  category?: string | undefined
}): AssetInput[] {
  const terms = args.query.trim().toLowerCase().split(/\s+/).filter(Boolean)

  return MCP_CATALOG_ITEMS.filter((item) => {
    if (args.category && item.category !== args.category) return false
    const haystack = [item.id, item.name, item.category, ...(item.tags ?? [])]
      .join(' ')
      .toLowerCase()
    return terms.every((term) => haystack.includes(term))
  })
}
