import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { isPaintOnlyUnit } from '@pascal-app/core'
import {
  achievedBetween,
  facadeAppliedResult,
  facadeRequests,
  facadeSetSummary,
  facadeTargetsFor,
  planAgentFacadeSet,
  requireBalconiesKept,
  requireFacadeFits,
  requireFacadePreviewed,
} from '@pascal-app/core/agent-operations'
import {
  applyFacadeOutput,
  applyFacadeSetTool,
  applyFacadeTool,
  facadePreviewOutput,
  isAgentRefusal,
  previewFacadeUnitTool,
} from '@pascal-app/core/agent-tools'
import {
  type FacadeFillPlan,
  facadeAppliedSvg,
  facadeFillPatches,
  planFacadeFill,
  previewFacadeUnit,
} from '@pascal-app/core/building'
import type { AnyNode, WallNode } from '@pascal-app/core/schema'
import { z } from 'zod'
import type { SceneOperations } from '../operations'
import { DESTRUCTIVE_TOOL_ANNOTATIONS, READ_ONLY_TOOL_ANNOTATIONS } from './annotations'
import { ErrorCode, refusalResult, throwMcpError } from './errors'
import { liveSyncOutput, persistencePayload, publishLiveSceneSnapshot } from './live-sync'
import { registerPatchGuard } from './patch-guards'

/**
 * A facade owns what it generates and re-solves it on the next fill, so a patch editing or forging
 * one of those nodes would be silently undone: apply_patch refuses it.
 */
registerPatchGuard({
  name: 'facade-owned',
  order: 10,
  run(patches, nodes) {
    for (const [index, patch] of patches.entries()) {
      if (patch.op === 'upsert_material') continue
      const owner =
        patch.op === 'create'
          ? (patch.node as { metadata?: Record<string, unknown> }).metadata?.facadeOwner
          : nodes[patch.id]?.metadata?.facadeOwner
      if (owner)
        throwMcpError(
          ErrorCode.InvalidParams,
          `patches[${index}] targets a node generated by the facade on wall ${String(owner)}. Change the facade with apply_facade instead.`,
        )
    }
  },
})

/** The contract's result (core `facadeAppliedResult`), the MCP's drawing of it, and the live sync's note. */
const applyOutput = { ...applyFacadeOutput, elevationSvg: z.string(), ...liveSyncOutput }

export function registerFacadeTools(server: McpServer, bridge: SceneOperations): void {
  server.registerTool(
    previewFacadeUnitTool.name,
    {
      title: previewFacadeUnitTool.title,
      description: previewFacadeUnitTool.description,
      inputSchema: previewFacadeUnitTool.input,
      outputSchema: facadePreviewOutput,
      annotations: READ_ONLY_TOOL_ANNOTATIONS,
    },
    async (input) => {
      const payload = previewFacadeUnit(input)
      return {
        content: [{ type: 'text' as const, text: JSON.stringify(payload) }],
        structuredContent: payload,
      }
    },
  )

  server.registerTool(
    applyFacadeTool.name,
    {
      title: applyFacadeTool.title,
      description: applyFacadeTool.description,
      inputSchema: applyFacadeTool.input,
      outputSchema: applyOutput,
      annotations: DESTRUCTIVE_TOOL_ANNOTATIONS,
    },
    async ({
      wallId,
      wallIds,
      levelIds,
      scope,
      unit,
      previewId,
      replaceExisting,
      replaceBalconies,
      mode,
      joinTolerance,
    }) => {
      const requests = facadeRequests({
        wallId,
        wallIds,
        levelIds,
        scope,
        joinTolerance,
        paintOnly: isPaintOnlyUnit(unit),
      })
      // A copy: a bridge may write into the map it hands out.
      const before = { ...bridge.getNodes() } as Record<string, AnyNode>
      const plans: FacadeFillPlan[] = []
      const leftOut: NonNullable<ReturnType<typeof facadeTargetsFor>['leftOut']> = []
      const curved: NonNullable<ReturnType<typeof facadeTargetsFor>['curved']> = []
      const applied: WallNode[] = []
      // Every floor is planned before any is written, so a unit that fits none is refused whole.
      try {
        requireFacadePreviewed([{ unit }], [previewId])
        for (const request of requests) {
          const nodes = bridge.getNodes() as Record<string, AnyNode>
          const targets = facadeTargetsFor(nodes, request)
          const plan = planFacadeFill({ ...targets, nodes, unit, replaceExisting, mode })
          requireFacadeFits(plan, unit, mode)
          requireBalconiesKept(plan, replaceBalconies)
        }
      } catch (error) {
        if (isAgentRefusal(error)) return refusalResult(error)
        throwMcpError(
          ErrorCode.InvalidParams,
          error instanceof Error ? error.message : String(error),
        )
      }
      for (const request of requests) {
        const nodes = bridge.getNodes() as Record<string, AnyNode>
        let patches: ReturnType<typeof facadeFillPatches>
        let plan: FacadeFillPlan
        try {
          const { leftOut: past, curved: arcs, ...targets } = facadeTargetsFor(nodes, request)
          leftOut.push(...(past ?? []))
          curved.push(...(arcs ?? []))
          plan = planFacadeFill({ ...targets, nodes, unit, replaceExisting, mode })
          patches = facadeFillPatches(plan, nodes)
        } catch (error) {
          if (isAgentRefusal(error)) return refusalResult(error)
          throwMcpError(
            ErrorCode.InvalidParams,
            error instanceof Error ? error.message : String(error),
          )
        }
        if (patches.length) bridge.applyPatch(patches)
        plans.push(plan)
        applied.push(...plan.walls.map((entry) => entry.wall))
      }
      const persistence = await publishLiveSceneSnapshot(bridge, 'apply_facade')
      const after = bridge.getNodes() as Record<string, AnyNode>
      const payload = {
        ...facadeAppliedResult({
          plans,
          leftOut,
          curved,
          achieved: achievedBetween(before, after),
        }),
        elevationSvg: facadeAppliedSvg(
          bridge.getNodes() as Record<string, AnyNode>,
          applied,
          unit.paint,
        ),
        ...persistencePayload(persistence),
      }
      return {
        content: [{ type: 'text' as const, text: JSON.stringify(payload) }],
        structuredContent: payload,
      }
    },
  )

  server.registerTool(
    applyFacadeSetTool.name,
    {
      title: applyFacadeSetTool.title,
      description: applyFacadeSetTool.description,
      inputSchema: applyFacadeSetTool.input,
      annotations: DESTRUCTIVE_TOOL_ANNOTATIONS,
    },
    async (input) => {
      let plan: ReturnType<typeof planAgentFacadeSet>
      try {
        requireFacadePreviewed(input.set.units, input.previewIds)
        plan = planAgentFacadeSet(bridge.getNodes() as Record<string, AnyNode>, input as never, {
          activeLevelId: null,
        })
      } catch (error) {
        if (isAgentRefusal(error)) return refusalResult(error)
        throwMcpError(
          ErrorCode.InvalidParams,
          error instanceof Error ? error.message : String(error),
        )
      }
      // A copy: a bridge may write into the map it hands out.
      const before = { ...bridge.getNodes() } as Record<string, AnyNode>
      if (plan.patches.length) bridge.applyPatch(plan.patches)
      const persistence = await publishLiveSceneSnapshot(bridge, 'apply_facade_set')
      const walls = plan.plans.flatMap((entry) => entry.walls.map((wall) => wall.wall))
      const payload = {
        ...facadeSetSummary(plan),
        achieved: achievedBetween(before, bridge.getNodes() as Record<string, AnyNode>),
        elevationSvg: facadeAppliedSvg(
          bridge.getNodes() as Record<string, AnyNode>,
          walls,
          input.set.units[0]?.unit.paint ?? {},
        ),
        ...persistencePayload(persistence),
      }
      return {
        content: [{ type: 'text' as const, text: JSON.stringify(payload) }],
        structuredContent: payload,
      }
    },
  )
}
