import { z } from 'zod'
import { BaseNode, nodeType, objectId } from '../base'
import { MaterialSchema } from '../material'

const CabinetCompartment = z.object({
  id: z.string(),
  type: z.enum([
    'shelf',
    'drawer',
    'door',
    'oven',
    'microwave',
    'dishwasher',
    'cooktop-gas',
    'cooktop-induction',
    'pull-out-pantry',
    'fridge-single',
    'fridge-double',
    'fridge-top-freezer',
    'fridge-bottom-freezer',
    'hood-pyramid',
    'hood-curved-glass',
  ]),
  height: z.number().positive().max(2.5).optional(),
  doorType: z.enum(['single-left', 'single-right', 'double', 'glass']).optional(),
  drawerCount: z.number().int().min(1).max(6).optional(),
  shelfCount: z.number().int().min(0).max(8).optional(),
  pantryRackStyle: z.enum(['wire', 'tray', 'glass']).optional(),
  cooktopBurnersOn: z.boolean().optional(),
  cooktopActiveBurners: z.array(z.number().int().min(0).max(8)).optional(),
  cooktopKnobProgress: z.array(z.number().min(0).max(1)).optional(),
  cooktopShowGrate: z.boolean().optional(),
  cooktopLayout: z
    .enum([
      'gas-2burner',
      'gas-4burner',
      'gas-5burner-wok',
      'gas-6burner',
      'induction-2zone',
      'induction-4zone',
    ])
    .optional(),
})

export const CabinetNode = BaseNode.extend({
  id: objectId('cabinet'),
  type: nodeType('cabinet'),
  position: z.tuple([z.number(), z.number(), z.number()]).default([0, 0, 0]),
  rotation: z.number().default(0),
  runTier: z.enum(['base', 'wall', 'tall']).default('base'),
  children: z.array(objectId('cabinet-module')).default([]),
  width: z.number().min(0.3).max(3).default(0.6),
  depth: z.number().min(0.3).max(1.2).default(0.58),
  carcassHeight: z.number().min(0.4).max(2.4).default(0.72),
  operationState: z.number().min(0).max(1).default(0),
  plinthHeight: z.number().min(0).max(0.3).default(0.1),
  toeKickDepth: z.number().min(0).max(0.2).default(0.075),
  boardThickness: z.number().min(0.01).max(0.08).default(0.018),
  countertopThickness: z.number().min(0).max(0.08).default(0.02),
  countertopOverhang: z.number().min(0).max(0.12).default(0.02),
  frontThickness: z.number().min(0.01).max(0.05).default(0.018),
  frontGap: z.number().min(0.001).max(0.02).default(0.003),
  doorStyle: z.enum(['single-left', 'single-right', 'double', 'glass']).default('double'),
  handleStyle: z.enum(['none', 'bar', 'cutout', 'hole', 'knob']).default('bar'),
  handlePosition: z.enum(['auto', 'top', 'center', 'edge']).default('auto'),
  frontOverlay: z.enum(['full', 'inset']).default('full'),
  withBottomPanel: z.boolean().default(true),
  showPlinth: z.boolean().default(true),
  withCountertop: z.boolean().default(true),
  material: MaterialSchema.optional(),
  materialPreset: z.string().optional(),
  slots: z.record(z.string(), z.string()).optional(),
  stack: z.array(CabinetCompartment).optional(),
}).describe('Parametric modular cabinet run node')

export const CabinetModuleNode = BaseNode.extend({
  id: objectId('cabinet-module'),
  type: nodeType('cabinet-module'),
  position: z.tuple([z.number(), z.number(), z.number()]).default([0, 0, 0]),
  rotation: z.number().default(0),
  children: z.array(objectId('cabinet-module')).default([]),
  cabinetType: z.enum(['base', 'tall']).default('base'),
  width: z.number().min(0.3).max(3).default(0.6),
  depth: z.number().min(0.3).max(1.2).default(0.58),
  carcassHeight: z.number().min(0.4).max(2.4).default(0.72),
  operationState: z.number().min(0).max(1).default(0),
  plinthHeight: z.number().min(0).max(0.3).default(0.1),
  toeKickDepth: z.number().min(0).max(0.2).default(0.075),
  boardThickness: z.number().min(0.01).max(0.08).default(0.018),
  countertopThickness: z.number().min(0).max(0.08).default(0.02),
  countertopOverhang: z.number().min(0).max(0.12).default(0.02),
  frontThickness: z.number().min(0.01).max(0.05).default(0.018),
  frontGap: z.number().min(0.001).max(0.02).default(0.003),
  doorStyle: z.enum(['single-left', 'single-right', 'double', 'glass']).default('double'),
  handleStyle: z.enum(['none', 'bar', 'cutout', 'hole', 'knob']).default('bar'),
  handlePosition: z.enum(['auto', 'top', 'center', 'edge']).default('auto'),
  frontOverlay: z.enum(['full', 'inset']).default('full'),
  withBottomPanel: z.boolean().default(true),
  showPlinth: z.boolean().default(true),
  withCountertop: z.boolean().default(true),
  material: MaterialSchema.optional(),
  materialPreset: z.string().optional(),
  slots: z.record(z.string(), z.string()).optional(),
  stack: z.array(CabinetCompartment).optional(),
}).describe('Parametric module inside a modular cabinet run')

export type CabinetNode = z.infer<typeof CabinetNode>
export type CabinetModuleNode = z.infer<typeof CabinetModuleNode>
