import type { AssetInput } from '@pascal-app/core'

/** Items downloaded from Supabase: have thumbnail.png + floor-plan.png */
function supabase(id: string) {
  return {
    thumbnail: `/items/${id}/thumbnail.png`,
    src: `/items/${id}/model.glb`,
    floorPlanUrl: `/items/${id}/floor-plan.png`,
  } as const
}

/** Items that only exist locally: have thumbnail.webp, no floorPlanUrl */
function localOnly(id: string) {
  return {
    thumbnail: `/items/${id}/thumbnail.webp`,
    src: `/items/${id}/model.glb`,
  } as const
}

function iconOnly(id: string, thumbnail: string) {
  return {
    thumbnail,
    src: `/items/${id}/model.glb`,
  } as const
}

export const CATALOG_ITEMS: AssetInput[] = [
  // ═══════════════════════════════════════════════════════════════════
  // SAFETY / FIRE
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sprinkler',
    category: 'safety',
    name: 'Sprinkler',
    tags: ['ceiling', 'safety'],
    ...supabase('sprinkler'),
    dimensions: [0.09, 0.04, 0.09],
    offset: [0, 0.0386, 0],
    rotation: [Math.PI, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
  },
  {
    id: 'smoke-detector',
    category: 'safety',
    name: 'Smoke Detector',
    tags: ['ceiling', 'safety'],
    ...supabase('smoke-detector'),
    dimensions: [0.16, 0.05, 0.16],
    offset: [0, 0.0492, 0],
    rotation: [Math.PI, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
  },
  {
    id: 'fire-detector',
    category: 'safety',
    name: 'Fire Detector',
    tags: ['wall', 'safety'],
    ...supabase('fire-detector'),
    dimensions: [0.12, 0.19, 0.07],
    offset: [0.0281, 0.012, 0.0015],
    rotation: [0, 0, 0],
    scale: [0.9, 1.4, 0.7],
    attachTo: 'wall',
  },
  {
    id: 'fire-alarm',
    category: 'safety',
    name: 'Fire Alarm',
    tags: ['wall', 'safety'],
    ...localOnly('fire-alarm'),
    dimensions: [0.12, 0.12, 0.04],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'fire-extinguisher',
    category: 'safety',
    name: 'Fire Extinguisher',
    tags: ['wall', 'safety'],
    ...localOnly('fire-extinguisher'),
    dimensions: [0.22, 0.5, 0.22],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'hydrant',
    category: 'safety',
    name: 'Hydrant',
    tags: ['floor', 'safety', 'water'],
    ...supabase('hydrant'),
    dimensions: [0.64, 0.88, 0.64],
    offset: [-0.0046, 0, -0.0008],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'exit-sign',
    category: 'safety',
    name: 'Exit Sign',
    tags: ['wall', 'safety', 'signage'],
    ...supabase('exit-sign'),
    dimensions: [0.54, 0.27, 0.1],
    offset: [0, 0.0036, 0.0452],
    rotation: [0, 0, 0],
    scale: [0.6, 0.5, 0.7],
    attachTo: 'wall-side',
  },

  // ═══════════════════════════════════════════════════════════════════
  // ELECTRICAL
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'electric-panel',
    category: 'electrical',
    name: 'Electric Panel',
    tags: ['wall', 'electrical', 'utility'],
    ...supabase('electric-panel'),
    dimensions: [0.4, 0.98, 0.11],
    offset: [0, 0.0036, 0.0611],
    rotation: [0, 0, 0],
    scale: [0.61, 0.74, 0.7],
    attachTo: 'wall-side',
  },
  {
    id: 'ev-wall-charger',
    category: 'electrical',
    name: 'EV Wall Charger',
    tags: ['wall', 'electric', 'vehicle'],
    ...supabase('ev-wall-charger'),
    dimensions: [0.29, 0.65, 0.17],
    offset: [-0.0677, 0.2979, 0.1503],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
  {
    id: 'thermostat',
    category: 'electrical',
    name: 'Thermostat',
    tags: ['wall', 'climate', 'electrical'],
    ...supabase('thermostat'),
    dimensions: [0.1, 0.1, 0.01],
    offset: [0, 0.0013, 0.0022],
    rotation: [0, 0, 0],
    scale: [2.08, 2.1, 2.59],
    attachTo: 'wall-side',
  },
  {
    id: 'alarm-keypad',
    category: 'electrical',
    name: 'Alarm Keypad',
    tags: ['wall', 'security', 'electronic'],
    ...supabase('alarm-keypad'),
    dimensions: [0.18, 0.13, 0.03],
    offset: [0, 0.0671, -0.0002],
    rotation: [1.5708, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'factory-electric-box',
    category: 'electrical',
    name: 'Factory Electric Box',
    tags: ['floor', 'electrical', 'industrial', 'factory'],
    ...iconOnly('factory-electric-box', '/icons/appliance.png'),
    dimensions: [0.65, 1.0, 0.45],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },

  // ═══════════════════════════════════════════════════════════════════
  // CLIMATE / APPLIANCES
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'ac-block',
    category: 'electrical',
    name: 'AC Block',
    tags: ['floor', 'electrical', 'cooling'],
    ...supabase('ac-block'),
    dimensions: [1.06, 0.95, 1.06],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [0.79, 0.79, 0.79],
  },
  {
    id: 'air-conditioning',
    category: 'electrical',
    name: 'Air Conditioning',
    tags: ['wall', 'electrical', 'cooling'],
    ...supabase('air-conditioning'),
    dimensions: [1.56, 0.6, 0.41],
    offset: [0, 0.3, 0.2018],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'air-conditioner',
    category: 'electrical',
    name: 'Air Conditioner',
    tags: ['wall', 'electrical', 'cooling'],
    ...localOnly('air-conditioner'),
    dimensions: [1.0, 0.4, 0.3],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'air-conditioner-block',
    category: 'electrical',
    name: 'AC Condenser',
    tags: ['floor', 'electrical', 'outdoor'],
    ...localOnly('air-conditioner-block'),
    dimensions: [1.0, 0.8, 0.4],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ceiling-fan',
    category: 'electrical',
    name: 'Ceiling Fan',
    tags: ['ceiling', 'electrical', 'ventilation'],
    ...supabase('ceiling-fan'),
    dimensions: [0.92, 0.35, 1.04],
    offset: [-0.1371, 0.3448, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    interactive: {
      controls: [{ kind: 'toggle' as const }],
      effects: [{ kind: 'animation' as const, clips: { on: 'On' } }],
    },
  },
  {
    id: 'freezer',
    category: 'electrical',
    name: 'Freezer',
    tags: ['floor', 'cold-storage', 'appliance'],
    ...localOnly('freezer'),
    dimensions: [0.7, 1.8, 0.7],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },

  // ═══════════════════════════════════════════════════════════════════
  // LIGHTING
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'recessed-light',
    category: 'lighting',
    name: 'Recessed Light',
    tags: ['ceiling', 'lighting'],
    ...supabase('recessed-light'),
    dimensions: [0.23, 0.06, 0.23],
    offset: [0, 0.0057, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    interactive: {
      controls: [
        { kind: 'toggle' as const },
        { kind: 'slider' as const, label: 'Intensity', min: 0, max: 100, unit: '%', displayMode: 'dial' as const, default: 100 },
      ],
      effects: [{ kind: 'light' as const, intensityRange: [0, 2], color: '#ffffff', offset: [0, -0.1, 0] }],
    },
  },
  {
    id: 'ceiling-lamp',
    category: 'lighting',
    name: 'Ceiling Lamp',
    tags: ['ceiling', 'lighting'],
    ...supabase('ceiling-lamp'),
    dimensions: [0.55, 0.86, 0.55],
    offset: [0, 0.8545, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    interactive: {
      controls: [
        { kind: 'toggle' as const },
        { kind: 'slider' as const, label: 'Intensity', min: 0, max: 100, unit: '%', displayMode: 'dial' as const, default: 100 },
      ],
      effects: [{ kind: 'light' as const, intensityRange: [0, 2], color: '#ffffff', offset: [0, -0.3, 0] }],
    },
  },
  {
    id: 'ceiling-light',
    category: 'lighting',
    name: 'Ceiling Light',
    tags: ['ceiling', 'lighting'],
    ...localOnly('ceiling-light'),
    dimensions: [0.6, 0.12, 0.6],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    interactive: {
      controls: [
        { kind: 'toggle' as const },
        { kind: 'slider' as const, label: 'Intensity', min: 0, max: 100, unit: '%', displayMode: 'dial' as const, default: 100 },
      ],
      effects: [{ kind: 'light' as const, intensityRange: [0, 2], color: '#ffffff', offset: [0, -0.2, 0] }],
    },
  },
  {
    id: 'circular-ceiling-light',
    category: 'lighting',
    name: 'Circular Ceiling Light',
    tags: ['ceiling', 'lighting'],
    ...localOnly('circular-ceiling-light'),
    dimensions: [0.6, 0.1, 0.6],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    interactive: {
      controls: [
        { kind: 'toggle' as const },
        { kind: 'slider' as const, label: 'Intensity', min: 0, max: 100, unit: '%', displayMode: 'dial' as const, default: 100 },
      ],
      effects: [{ kind: 'light' as const, intensityRange: [0, 2], color: '#ffffff', offset: [0, -0.2, 0] }],
    },
  },
  {
    id: 'rectangular-ceiling-light',
    category: 'lighting',
    name: 'Rectangular Ceiling Light',
    tags: ['ceiling', 'lighting'],
    ...localOnly('rectangular-ceiling-light'),
    dimensions: [1.2, 0.08, 0.35],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    interactive: {
      controls: [
        { kind: 'toggle' as const },
        { kind: 'slider' as const, label: 'Intensity', min: 0, max: 100, unit: '%', displayMode: 'dial' as const, default: 100 },
      ],
      effects: [{ kind: 'light' as const, intensityRange: [0, 2], color: '#ffffff', offset: [0, -0.2, 0] }],
    },
  },
  {
    id: 'floor-lamp',
    category: 'lighting',
    name: 'Floor Lamp',
    tags: ['floor', 'lighting'],
    ...supabase('floor-lamp'),
    dimensions: [0.7, 1.86, 0.69],
    offset: [0.0341, 0.0045, 0.0219],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    interactive: {
      controls: [
        { kind: 'toggle' as const },
        { kind: 'slider' as const, label: 'Intensity', min: 0, max: 100, unit: '%', displayMode: 'dial' as const, default: 100 },
      ],
      effects: [{ kind: 'light' as const, intensityRange: [0, 2], color: '#ffffff', offset: [0, 1.4, 0] }],
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // ELECTRONICS / MONITORING
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'computer',
    category: 'electronics',
    name: 'Computer',
    tags: ['countertop', 'electronics', 'workstation'],
    ...supabase('computer'),
    dimensions: [0.68, 0.48, 0.19],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'television',
    category: 'electronics',
    name: 'Television',
    tags: ['floor', 'electronics', 'monitoring'],
    ...supabase('television'),
    dimensions: [1.62, 1.07, 0.38],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'flat-screen-tv',
    category: 'electronics',
    name: 'Flat Screen TV',
    tags: ['wall', 'electronics', 'monitoring'],
    ...localOnly('flat-screen-tv'),
    dimensions: [1.4, 0.9, 0.08],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'stereo-speaker',
    category: 'electronics',
    name: 'Stereo Speaker',
    tags: ['floor', 'electronics', 'audio'],
    ...supabase('stereo-speaker'),
    dimensions: [0.23, 1, 0.34],
    offset: [0, 0, -0.0129],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },

  // ═══════════════════════════════════════════════════════════════════
  // INDUSTRIAL EQUIPMENT
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sewing-machine',
    category: 'equipment',
    name: 'Sewing Machine',
    tags: ['countertop', 'equipment', 'industrial'],
    ...supabase('sewing-machine'),
    dimensions: [0.83, 0.68, 0.32],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shelf',
    category: 'equipment',
    name: 'Shelf',
    tags: ['wall', 'storage', 'shelving'],
    ...supabase('shelf'),
    dimensions: [0.74, 0.04, 0.32],
    offset: [0, 0.02, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
    surface: { height: 0.04 },
  },
  {
    id: 'trash-bin',
    category: 'equipment',
    name: 'Trash Bin',
    tags: ['floor', 'waste'],
    ...supabase('trash-bin'),
    dimensions: [0.35, 0.59, 0.42],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'desk',
    category: 'equipment',
    name: 'Desk',
    tags: ['floor', 'office', 'furniture', 'factory'],
    ...localOnly('desk'),
    dimensions: [1.82, 0.92, 0.85],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.92 },
  },
  {
    id: 'office-chair',
    category: 'equipment',
    name: 'Office Chair',
    tags: ['floor', 'office', 'furniture', 'factory'],
    ...localOnly('office-chair'),
    floorPlanUrl: '/items/office-chair/floor-plan.svg',
    dimensions: [0.65, 1.16, 0.69],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'barbell',
    category: 'equipment',
    name: 'Barbell',
    tags: ['floor', 'fitness', 'equipment', 'factory'],
    ...localOnly('barbell'),
    dimensions: [0.38, 0.38, 1.72],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'basket-hoop',
    category: 'equipment',
    name: 'Basket Hoop',
    tags: ['floor', 'recreation', 'equipment', 'factory'],
    ...localOnly('basket-hoop'),
    dimensions: [0.67, 1.77, 0.56],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'coat-rack',
    category: 'equipment',
    name: 'Coat Rack',
    tags: ['floor', 'storage', 'utility'],
    ...supabase('coat-rack'),
    dimensions: [0.33, 1.76, 0.33],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'factory-straight-pipe',
    category: 'equipment',
    name: 'Factory Straight Pipe',
    tags: ['floor', 'pipe', 'industrial', 'factory'],
    ...iconOnly('factory-straight-pipe', '/icons/shelf.png'),
    dimensions: [1.6, 0.4, 0.4],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'factory-curved-pipe',
    category: 'equipment',
    name: 'Factory Curved Pipe',
    tags: ['floor', 'pipe', 'industrial', 'factory'],
    ...iconOnly('factory-curved-pipe', '/icons/shelf.png'),
    dimensions: [1.0, 0.75, 1.0],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'factory-t-pipe',
    category: 'equipment',
    name: 'Factory T Pipe',
    tags: ['floor', 'pipe', 'industrial', 'factory'],
    ...iconOnly('factory-t-pipe', '/icons/shelf.png'),
    dimensions: [1.35, 0.55, 1.0],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'factory-extractor',
    category: 'equipment',
    name: 'Factory Extractor',
    tags: ['floor', 'ventilation', 'industrial', 'factory'],
    ...iconOnly('factory-extractor', '/icons/appliance.png'),
    dimensions: [0.9, 1.4, 0.9],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'factory-barrel',
    category: 'equipment',
    name: 'Factory Barrel',
    tags: ['floor', 'barrel', 'storage', 'industrial'],
    ...iconOnly('factory-barrel', '/icons/shelf.png'),
    dimensions: [0.6, 0.9, 0.6],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },

  // ═══════════════════════════════════════════════════════════════════
  // STRUCTURAL
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'bathroom-sink',
    category: 'equipment',
    name: 'Bathroom Sink',
    tags: ['floor', 'bathroom', 'plumbing'],
    ...localOnly('bathroom-sink'),
    dimensions: [0.6, 0.85, 0.5],
  },
  {
    id: 'bathtub',
    category: 'equipment',
    name: 'Bathtub',
    tags: ['floor', 'bathroom', 'plumbing'],
    ...localOnly('bathtub'),
    dimensions: [1.7, 0.55, 0.75],
  },
  {
    id: 'bedside-table',
    category: 'equipment',
    name: 'Bedside Table',
    tags: ['floor', 'furniture', 'storage'],
    ...localOnly('bedside-table'),
    dimensions: [0.5, 0.55, 0.45],
    surface: { height: 0.55 },
  },
  {
    id: 'bookshelf',
    category: 'equipment',
    name: 'Bookshelf',
    tags: ['floor', 'office', 'storage', 'furniture'],
    ...localOnly('bookshelf'),
    dimensions: [0.8, 1.8, 0.35],
  },
  {
    id: 'closet',
    category: 'equipment',
    name: 'Closet',
    tags: ['floor', 'storage', 'furniture'],
    ...localOnly('closet'),
    dimensions: [1.2, 2, 0.6],
  },
  {
    id: 'coffee-table',
    category: 'equipment',
    name: 'Coffee Table',
    tags: ['floor', 'office', 'furniture'],
    ...localOnly('coffee-table'),
    dimensions: [1, 0.45, 0.6],
    surface: { height: 0.45 },
  },
  {
    id: 'dining-chair',
    category: 'equipment',
    name: 'Dining Chair',
    tags: ['floor', 'office', 'furniture', 'seating'],
    ...localOnly('dining-chair'),
    dimensions: [0.48, 0.9, 0.52],
  },
  {
    id: 'dining-table',
    category: 'equipment',
    name: 'Dining Table',
    tags: ['floor', 'office', 'furniture'],
    ...localOnly('dining-table'),
    dimensions: [1.6, 0.75, 0.9],
    surface: { height: 0.75 },
  },
  {
    id: 'double-bed',
    category: 'equipment',
    name: 'Double Bed',
    tags: ['floor', 'furniture'],
    ...localOnly('double-bed'),
    dimensions: [2, 0.6, 1.6],
  },
  {
    id: 'dresser',
    category: 'equipment',
    name: 'Dresser',
    tags: ['floor', 'storage', 'furniture'],
    ...localOnly('dresser'),
    dimensions: [0.9, 0.9, 0.45],
    surface: { height: 0.9 },
  },
  {
    id: 'fridge',
    category: 'equipment',
    name: 'Fridge',
    tags: ['floor', 'kitchen', 'appliance'],
    ...localOnly('fridge'),
    dimensions: [0.75, 1.8, 0.7],
  },
  {
    id: 'kitchen',
    category: 'equipment',
    name: 'Kitchen',
    tags: ['floor', 'kitchen', 'appliance'],
    ...localOnly('kitchen'),
    dimensions: [2, 2, 0.7],
  },
  {
    id: 'kitchen-counter',
    category: 'equipment',
    name: 'Kitchen Counter',
    tags: ['floor', 'kitchen', 'countertop'],
    ...localOnly('kitchen-counter'),
    dimensions: [1.2, 0.9, 0.6],
    surface: { height: 0.9 },
  },
  {
    id: 'livingroom-chair',
    category: 'equipment',
    name: 'Livingroom Chair',
    tags: ['floor', 'office', 'furniture', 'seating'],
    ...localOnly('livingroom-chair'),
    dimensions: [0.75, 0.85, 0.75],
  },
  {
    id: 'lounge-chair',
    category: 'equipment',
    name: 'Lounge Chair',
    tags: ['floor', 'office', 'furniture', 'seating'],
    ...localOnly('lounge-chair'),
    dimensions: [0.75, 0.9, 0.85],
  },
  {
    id: 'single-bed',
    category: 'equipment',
    name: 'Single Bed',
    tags: ['floor', 'furniture'],
    ...localOnly('single-bed'),
    dimensions: [2, 0.55, 1],
  },
  {
    id: 'sofa',
    category: 'equipment',
    name: 'Sofa',
    tags: ['floor', 'office', 'furniture', 'seating'],
    ...localOnly('sofa'),
    floorPlanUrl: '/items/sofa/floor-plan.svg',
    dimensions: [2, 0.85, 0.9],
  },
  {
    id: 'stove',
    category: 'equipment',
    name: 'Stove',
    tags: ['floor', 'kitchen', 'appliance'],
    ...localOnly('stove'),
    dimensions: [0.6, 0.9, 0.6],
  },
  {
    id: 'toy',
    category: 'equipment',
    name: 'Toy',
    tags: ['floor', 'recreation'],
    ...localOnly('toy'),
    dimensions: [0.35, 0.35, 0.35],
  },
  {
    id: 'washing-machine',
    category: 'equipment',
    name: 'Washing Machine',
    tags: ['floor', 'appliance', 'utility'],
    ...localOnly('washing-machine'),
    dimensions: [0.6, 0.9, 0.6],
  },
  {
    id: 'barbell-stand',
    category: 'equipment',
    name: 'Barbell Stand',
    tags: ['floor', 'fitness', 'equipment', 'factory'],
    ...localOnly('barbell-stand'),
    dimensions: [1.1, 1.2, 0.8],
  },
  {
    id: 'bean-bag',
    category: 'equipment',
    name: 'Bean Bag',
    tags: ['floor', 'office', 'furniture', 'seating'],
    ...localOnly('bean-bag'),
    dimensions: [0.9, 0.55, 0.9],
  },
  {
    id: 'books',
    category: 'equipment',
    name: 'Books',
    tags: ['countertop', 'office', 'decor'],
    ...localOnly('books'),
    dimensions: [0.35, 0.25, 0.25],
  },
  {
    id: 'bunkbed',
    category: 'equipment',
    name: 'Bunkbed',
    tags: ['floor', 'furniture'],
    ...localOnly('bunkbed'),
    dimensions: [2, 1.7, 1],
  },
  {
    id: 'coffee-machine',
    category: 'equipment',
    name: 'Coffee Machine',
    tags: ['countertop', 'office', 'kitchen', 'appliance'],
    ...localOnly('coffee-machine'),
    dimensions: [0.25, 0.35, 0.3],
  },
  {
    id: 'couch-medium',
    category: 'equipment',
    name: 'Couch Medium',
    tags: ['floor', 'office', 'furniture', 'seating'],
    ...localOnly('couch-medium'),
    dimensions: [1.8, 0.85, 0.85],
  },
  {
    id: 'couch-small',
    category: 'equipment',
    name: 'Couch Small',
    tags: ['floor', 'office', 'furniture', 'seating'],
    ...localOnly('couch-small'),
    dimensions: [1.2, 0.85, 0.85],
  },
  {
    id: 'cutting-board',
    category: 'equipment',
    name: 'Cutting Board',
    tags: ['countertop', 'kitchen'],
    ...localOnly('cutting-board'),
    dimensions: [0.45, 0.04, 0.3],
  },
  {
    id: 'frying-pan',
    category: 'equipment',
    name: 'Frying Pan',
    tags: ['countertop', 'kitchen'],
    ...localOnly('frying-pan'),
    dimensions: [0.25, 0.08, 0.45],
  },
  {
    id: 'herman-miller-aeron-mo8x36k9',
    category: 'equipment',
    name: 'Herman Miller Aeron',
    tags: ['floor', 'office', 'furniture', 'seating'],
    ...supabase('herman-miller-aeron-mo8x36k9'),
    dimensions: [0.65, 1.16, 0.69],
  },
  {
    id: 'hood',
    category: 'equipment',
    name: 'Hood',
    tags: ['floor', 'kitchen', 'ventilation'],
    ...localOnly('hood'),
    dimensions: [0.8, 0.4, 0.5],
  },
  {
    id: 'iron',
    category: 'equipment',
    name: 'Iron',
    tags: ['countertop', 'utility'],
    ...localOnly('iron'),
    dimensions: [0.28, 0.15, 0.12],
  },
  {
    id: 'ironing-board',
    category: 'equipment',
    name: 'Ironing Board',
    tags: ['floor', 'utility'],
    ...localOnly('ironing-board'),
    dimensions: [1.2, 0.9, 0.35],
  },
  {
    id: 'kettle',
    category: 'equipment',
    name: 'Kettle',
    tags: ['countertop', 'kitchen', 'appliance'],
    ...localOnly('kettle'),
    dimensions: [0.2, 0.25, 0.2],
  },
  {
    id: 'kitchen-cabinet',
    category: 'equipment',
    name: 'Kitchen Cabinet',
    tags: ['floor', 'kitchen', 'storage'],
    ...localOnly('kitchen-cabinet'),
    dimensions: [0.8, 0.9, 0.6],
    surface: { height: 0.9 },
  },
  {
    id: 'kitchen-fridge',
    category: 'equipment',
    name: 'Kitchen Fridge',
    tags: ['floor', 'kitchen', 'appliance'],
    ...localOnly('kitchen-fridge'),
    dimensions: [0.7, 1.8, 0.7],
  },
  {
    id: 'kitchen-shelf',
    category: 'equipment',
    name: 'Kitchen Shelf',
    tags: ['floor', 'kitchen', 'storage'],
    ...localOnly('kitchen-shelf'),
    dimensions: [0.8, 0.3, 0.25],
    surface: { height: 0.3 },
  },
  {
    id: 'kitchen-utensils',
    category: 'equipment',
    name: 'Kitchen Utensils',
    tags: ['countertop', 'kitchen'],
    ...localOnly('kitchen-utensils'),
    dimensions: [0.35, 0.3, 0.25],
  },
  {
    id: 'laundry-bag',
    category: 'equipment',
    name: 'Laundry Bag',
    tags: ['floor', 'utility'],
    ...localOnly('laundry-bag'),
    dimensions: [0.45, 0.7, 0.45],
  },
  {
    id: 'microwave',
    category: 'equipment',
    name: 'Microwave',
    tags: ['countertop', 'kitchen', 'appliance'],
    ...localOnly('microwave'),
    dimensions: [0.5, 0.32, 0.4],
  },
  {
    id: 'office-table',
    category: 'equipment',
    name: 'Office Table',
    tags: ['floor', 'office', 'furniture', 'factory'],
    ...localOnly('office-table'),
    dimensions: [1.4, 0.75, 0.75],
    surface: { height: 0.75 },
  },
  {
    id: 'piano',
    category: 'equipment',
    name: 'Piano',
    tags: ['floor', 'office', 'recreation'],
    ...localOnly('piano'),
    dimensions: [1.4, 1.1, 0.6],
  },
  {
    id: 'rectangular-carpet',
    category: 'equipment',
    name: 'Rectangular Carpet',
    tags: ['floor', 'decor'],
    ...localOnly('rectangular-carpet'),
    dimensions: [1.6, 0.02, 2.3],
  },
  {
    id: 'round-carpet',
    category: 'equipment',
    name: 'Round Carpet',
    tags: ['floor', 'decor'],
    ...localOnly('round-carpet'),
    dimensions: [1.5, 0.02, 1.5],
  },
  {
    id: 'shower',
    category: 'equipment',
    name: 'Shower',
    tags: ['floor', 'bathroom', 'plumbing'],
    ...iconOnly('shower', '/icons/appliance.png'),
    dimensions: [0.9, 2, 0.9],
  },
  {
    id: 'shower-rug',
    category: 'equipment',
    name: 'Shower Rug',
    tags: ['floor', 'bathroom', 'decor'],
    ...localOnly('shower-rug'),
    dimensions: [0.8, 0.02, 0.5],
  },
  {
    id: 'sink-cabinet',
    category: 'equipment',
    name: 'Sink Cabinet',
    tags: ['floor', 'bathroom', 'storage'],
    ...localOnly('sink-cabinet'),
    dimensions: [0.8, 0.9, 0.55],
    surface: { height: 0.9 },
  },
  {
    id: 'small-kitchen-cabinet',
    category: 'equipment',
    name: 'Small Kitchen Cabinet',
    tags: ['floor', 'kitchen', 'storage'],
    ...localOnly('small-kitchen-cabinet'),
    dimensions: [0.6, 0.8, 0.45],
    surface: { height: 0.8 },
  },
  {
    id: 'standing-desk-mo8wgz95',
    category: 'equipment',
    name: 'Standing Desk',
    tags: ['floor', 'office', 'furniture', 'factory'],
    ...supabase('standing-desk-mo8wgz95'),
    dimensions: [1.4, 1.1, 0.75],
    surface: { height: 1.1 },
  },
  {
    id: 'stool',
    category: 'equipment',
    name: 'Stool',
    tags: ['floor', 'office', 'furniture', 'seating'],
    ...localOnly('stool'),
    dimensions: [0.4, 0.45, 0.4],
  },
  {
    id: 'table',
    category: 'equipment',
    name: 'Table',
    tags: ['floor', 'office', 'furniture'],
    ...localOnly('table'),
    dimensions: [1.2, 0.75, 0.8],
    surface: { height: 0.75 },
  },
  {
    id: 'threadmill',
    category: 'equipment',
    name: 'Treadmill',
    tags: ['floor', 'fitness', 'equipment', 'factory'],
    ...localOnly('threadmill'),
    dimensions: [0.8, 1.4, 1.8],
  },
  {
    id: 'toilet',
    category: 'equipment',
    name: 'Toilet',
    tags: ['floor', 'bathroom', 'plumbing'],
    ...localOnly('toilet'),
    dimensions: [0.4, 0.75, 0.7],
  },
  {
    id: 'tub',
    category: 'equipment',
    name: 'Tub',
    tags: ['floor', 'bathroom', 'plumbing'],
    ...iconOnly('tub', '/icons/appliance.png'),
    dimensions: [1.7, 0.55, 0.75],
  },
  {
    id: 'wall-sink',
    category: 'equipment',
    name: 'Wall Sink',
    tags: ['floor', 'bathroom', 'plumbing'],
    ...localOnly('wall-sink'),
    dimensions: [0.5, 0.45, 0.4],
  },
  {
    id: 'wine-bottle',
    category: 'equipment',
    name: 'Wine Bottle',
    tags: ['countertop', 'kitchen', 'decor'],
    ...localOnly('wine-bottle'),
    dimensions: [0.08, 0.3, 0.08],
  },
  {
    id: 'power-outlet-moa09g0o',
    category: 'electrical',
    name: 'Power Outlet',
    tags: ['wall', 'electrical', 'factory'],
    ...supabase('power-outlet-moa09g0o'),
    dimensions: [0.08, 0.08, 0.03],
    attachTo: 'wall-side',
  },
  {
    id: 'picture',
    category: 'equipment',
    name: 'Picture',
    tags: ['wall', 'office', 'decor'],
    ...localOnly('picture'),
    dimensions: [0.8, 0.6, 0.05],
    attachTo: 'wall-side',
  },
  {
    id: 'rectangular-mirror',
    category: 'equipment',
    name: 'Rectangular Mirror',
    tags: ['wall', 'bathroom', 'decor'],
    ...localOnly('rectangular-mirror'),
    dimensions: [0.6, 0.9, 0.05],
    attachTo: 'wall-side',
  },
  {
    id: 'round-mirror',
    category: 'equipment',
    name: 'Round Mirror',
    tags: ['wall', 'bathroom', 'decor'],
    ...localOnly('round-mirror'),
    dimensions: [0.6, 0.6, 0.05],
    attachTo: 'wall-side',
  },
  {
    id: 'wall-art-06',
    category: 'equipment',
    name: 'Wall Art',
    tags: ['wall', 'office', 'decor'],
    ...localOnly('wall-art-06'),
    dimensions: [0.8, 0.6, 0.05],
    attachTo: 'wall-side',
  },
  {
    id: 'table-lamp',
    category: 'lighting',
    name: 'Table Lamp',
    tags: ['countertop', 'lighting', 'office'],
    ...localOnly('table-lamp'),
    dimensions: [0.25, 0.5, 0.25],
  },
  {
    id: 'tv-stand',
    category: 'electronics',
    name: 'TV Stand',
    tags: ['floor', 'electronics', 'furniture'],
    ...localOnly('tv-stand'),
    dimensions: [1.4, 0.55, 0.45],
    surface: { height: 0.55 },
  },
  {
    id: '1967-chevrolet-camaro-moa24wsf',
    category: 'vehicle',
    name: '1967 Chevrolet Camaro',
    tags: ['floor', 'vehicle', 'car'],
    ...supabase('1967-chevrolet-camaro-moa24wsf'),
    dimensions: [1.9, 1.4, 4.8],
  },
  {
    id: 'car-toy',
    category: 'vehicle',
    name: 'Car Toy',
    tags: ['floor', 'vehicle', 'toy'],
    ...localOnly('car-toy'),
    dimensions: [0.35, 0.2, 0.65],
  },
  {
    id: 'exercise-bike',
    category: 'equipment',
    name: 'Exercise Bike',
    tags: ['floor', 'fitness', 'equipment', 'factory'],
    ...localOnly('exercise-bike'),
    dimensions: [0.6, 1.1, 1],
  },
  {
    id: 'skate',
    category: 'vehicle',
    name: 'Skate',
    tags: ['floor', 'vehicle', 'recreation'],
    ...localOnly('skate'),
    dimensions: [0.25, 0.15, 0.75],
  },
  {
    id: 'dishwasher-movn72ls',
    category: 'equipment',
    name: 'Dishwasher',
    tags: ['floor', 'kitchen', 'appliance'],
    ...supabase('dishwasher-movn72ls'),
    dimensions: [0.6, 0.85, 0.6],
  },

  {
    id: 'column',
    category: 'structural',
    name: 'Column',
    tags: ['floor', 'structural', 'architectural'],
    ...supabase('column'),
    dimensions: [0.5, 2.5, 0.5],
    offset: [0, 1.25, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'pillar',
    category: 'structural',
    name: 'Pillar',
    tags: ['floor', 'structural', 'stone'],
    ...supabase('pillar'),
    dimensions: [0.34, 1.26, 0.3],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'stairs',
    category: 'structural',
    name: 'Stairs',
    tags: ['floor', 'structural'],
    ...localOnly('stairs'),
    dimensions: [1.0, 3.0, 3.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },

  // ═══════════════════════════════════════════════════════════════════
  // INFRASTRUCTURE
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'parking-spot',
    category: 'infrastructure',
    name: 'Parking Spot',
    tags: ['floor', 'parking', 'pavement'],
    ...supabase('parking-spot'),
    dimensions: [4.95, 0.12, 2.28],
    offset: [0, 0.0121, 0.015],
    rotation: [0, 0, 0],
    scale: [0.9, 1, 0.78],
    surface: { height: 0.015 },
  },
  {
    id: 'fence',
    category: 'infrastructure',
    name: 'Fence',
    tags: ['floor', 'fencing', 'boundary'],
    ...localOnly('fence'),
    dimensions: [2.0, 1.2, 0.06],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'low-fence',
    category: 'infrastructure',
    name: 'Low Fence',
    tags: ['floor', 'fencing', 'boundary'],
    ...localOnly('low-fence'),
    dimensions: [2.0, 0.6, 0.06],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'medium-fence',
    category: 'infrastructure',
    name: 'Medium Fence',
    tags: ['floor', 'fencing', 'boundary'],
    ...localOnly('medium-fence'),
    dimensions: [2.0, 1.0, 0.06],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'high-fence',
    category: 'infrastructure',
    name: 'High Fence',
    tags: ['floor', 'fencing', 'security'],
    ...localOnly('high-fence'),
    dimensions: [2.0, 2.0, 0.06],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },

  // ═══════════════════════════════════════════════════════════════════
  // OPENINGS (Doors + Windows)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'door',
    category: 'opening',
    name: 'Door',
    tags: ['floor', 'door', 'entry'],
    ...localOnly('door'),
    dimensions: [1.0, 2.1, 0.1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'door-bar',
    category: 'opening',
    name: 'Door Bar',
    tags: ['floor', 'door', 'entry'],
    ...localOnly('door-bar'),
    dimensions: [1.0, 2.1, 0.12],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'door-with-bar',
    category: 'opening',
    name: 'Door with Bar',
    tags: ['floor', 'door', 'entry'],
    ...localOnly('door-with-bar'),
    dimensions: [1.0, 2.1, 0.15],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'doorway-front',
    category: 'opening',
    name: 'Doorway Front',
    tags: ['floor', 'door', 'entry'],
    ...localOnly('doorway-front'),
    dimensions: [1.0, 2.1, 0.2],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'glass-door',
    category: 'opening',
    name: 'Glass Door',
    tags: ['floor', 'door', 'glass'],
    ...localOnly('glass-door'),
    dimensions: [1.0, 2.1, 0.08],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'window-double',
    category: 'opening',
    name: 'Double Window',
    tags: ['wall', 'window'],
    ...localOnly('window-double'),
    dimensions: [2.0, 1.5, 0.1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
  {
    id: 'window-large',
    category: 'opening',
    name: 'Large Window',
    tags: ['wall', 'window'],
    ...localOnly('window-large'),
    dimensions: [2.4, 2.0, 0.1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
  {
    id: 'window-rectangle',
    category: 'opening',
    name: 'Rectangle Window',
    tags: ['wall', 'window'],
    ...localOnly('window-rectangle'),
    dimensions: [2.0, 1.5, 0.1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
  {
    id: 'window-round',
    category: 'opening',
    name: 'Round Window',
    tags: ['wall', 'window'],
    ...localOnly('window-round'),
    dimensions: [0.9, 0.9, 0.1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
  {
    id: 'window-simple',
    category: 'opening',
    name: 'Simple Window',
    tags: ['wall', 'window'],
    ...localOnly('window-simple'),
    dimensions: [1.5, 1.2, 0.1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
  {
    id: 'window-small',
    category: 'opening',
    name: 'Small Window',
    tags: ['wall', 'window'],
    ...localOnly('window-small'),
    dimensions: [0.8, 0.8, 0.1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
  {
    id: 'window-small-2',
    category: 'opening',
    name: 'Small Window 2',
    tags: ['wall', 'window'],
    ...localOnly('window-small-2'),
    dimensions: [0.7, 0.7, 0.1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
  {
    id: 'window-square',
    category: 'opening',
    name: 'Square Window',
    tags: ['wall', 'window'],
    ...localOnly('window-square'),
    dimensions: [1.2, 1.2, 0.1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
  {
    id: 'window1-black-open-1731',
    category: 'opening',
    name: 'Black Open Window',
    tags: ['wall', 'window'],
    ...localOnly('window1-black-open-1731'),
    dimensions: [1.0, 1.5, 0.1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },

  // ═══════════════════════════════════════════════════════════════════
  // NATURE / PLANTS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'cactus',
    category: 'nature',
    name: 'Cactus',
    tags: ['floor', 'plant', 'cactus', 'green'],
    ...supabase('cactus'),
    dimensions: [0.34, 0.39, 0.27],
    offset: [-0.0039, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'small-indoor-plant',
    category: 'nature',
    name: 'Small Plant',
    tags: ['countertop', 'plant', 'vegetation'],
    ...supabase('small-indoor-plant'),
    dimensions: [0.4, 0.67, 0.38],
    offset: [-0.0106, 0, 0.0067],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'indoor-plant',
    category: 'nature',
    name: 'Indoor Plant',
    tags: ['floor', 'plant', 'greenery', 'foliage'],
    ...supabase('indoor-plant'),
    dimensions: [0.69, 1.63, 0.83],
    offset: [-0.0506, 0, 0.0664],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bush',
    category: 'nature',
    name: 'Bush',
    tags: ['floor', 'plant', 'shrub', 'landscaping'],
    ...supabase('bush'),
    dimensions: [3, 1.04, 1.01],
    offset: [-0.1463, 0.0094, -0.113],
    rotation: [0, 0, 0],
    scale: [0.96, 0.96, 0.96],
  },
  {
    id: 'hedge',
    category: 'nature',
    name: 'Hedge',
    tags: ['floor', 'plant', 'hedge', 'landscaping'],
    ...localOnly('hedge'),
    dimensions: [3.0, 1.5, 1.0],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'palm',
    category: 'nature',
    name: 'Palm',
    tags: ['floor', 'tree', 'tropical', 'plant'],
    ...supabase('palm'),
    dimensions: [0.525, 4.5, 0.496],
    offset: [0, 0.08, 0],
    rotation: [0, 0, 0],
    scale: [0.37, 0.37, 0.37],
  },
  {
    id: 'fir-tree',
    category: 'nature',
    name: 'Fir',
    tags: ['floor', 'tree', 'evergreen', 'conifer'],
    ...supabase('fir-tree'),
    dimensions: [0.27, 3, 0.23],
    offset: [0.02, 0.05, -0.06],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tree',
    category: 'nature',
    name: 'Tree',
    tags: ['floor', 'tree', 'vegetation'],
    ...supabase('tree'),
    dimensions: [0.79, 5, 0.85],
    offset: [-0.02, 0.17, -0.04],
    rotation: [0, 0, 0],
    scale: [0.65, 0.65, 0.65],
  },
  {
    id: 'ball',
    category: 'nature',
    name: 'Stone Sphere',
    tags: ['floor', 'stone', 'sculpture', 'decor'],
    ...supabase('ball'),
    dimensions: [0.24, 0.24, 0.24],
    offset: [-0.0001, 0.1194, -0.0001],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },

  // ═══════════════════════════════════════════════════════════════════
  // OUTDOOR
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'patio-umbrella',
    category: 'outdoor',
    name: 'Patio Umbrella',
    tags: ['floor', 'outdoor', 'shade'],
    ...supabase('patio-umbrella'),
    dimensions: [0.14, 3.6, 0.15],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'outdoor-playhouse',
    category: 'outdoor',
    name: 'Outdoor Playhouse',
    tags: ['floor', 'outdoor', 'play'],
    ...supabase('outdoor-playhouse'),
    dimensions: [0.3, 0.47, 0.72],
    offset: [-0.0062, 0, -0.0268],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sunbed',
    category: 'outdoor',
    name: 'Sunbed',
    tags: ['floor', 'outdoor', 'leisure'],
    ...supabase('sunbed'),
    dimensions: [0.86, 1.13, 1.01],
    offset: [0, 0.0516, 0.0137],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'pool-table',
    category: 'equipment',
    name: 'Pool Table',
    tags: ['floor', 'equipment', 'gaming'],
    ...supabase('pool-table'),
    dimensions: [2.11, 0.98, 3.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },

  // ═══════════════════════════════════════════════════════════════════
  // VEHICLES
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'tesla',
    category: 'vehicle',
    name: 'Tesla Model Y',
    tags: ['floor', 'car', 'vehicle', 'electric'],
    ...supabase('tesla'),
    dimensions: [1.98, 1.62, 4.76],
    offset: [0.0039, -0.0102, -0.0148],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'scooter',
    category: 'vehicle',
    name: 'Scooter',
    tags: ['floor', 'scooter', 'transport', 'urban'],
    ...supabase('scooter'),
    dimensions: [0.85, 0.85, 0.45],
    offset: [0.1127, 0.0017, 0.1744],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
]

export function getDefaultCatalogItem(category: string | null | undefined): AssetInput | null {
  if (!category) return null
  return CATALOG_ITEMS.find((item) => item.category === category) ?? CATALOG_ITEMS[0] ?? null
}
